version: 2
project_name: miro-developer-platform-pp-cli
changelog:
  disable: true
builds:
  - id: miro-developer-platform-pp-cli
    main: ./cmd/miro-developer-platform-pp-cli
    binary: miro-developer-platform-pp-cli
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X miro-developer-platform-pp-cli/internal/cli.version={{ .Version }}
    targets:
      - darwin_amd64
      - darwin_arm64
      - linux_amd64
      - linux_arm64
      - windows_amd64
      - windows_arm64
  - id: miro-developer-platform-pp-mcp
    main: ./cmd/miro-developer-platform-pp-mcp
    binary: miro-developer-platform-pp-mcp
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
    targets:
      - darwin_amd64
      - darwin_arm64
      - linux_amd64
      - linux_arm64
      - windows_amd64
      - windows_arm64
archives:
  - formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: [zip]
checksum:
  name_template: checksums.txt
brews:
  - name: miro-developer-platform-pp-cli
    repository:
      owner: olga-safonova
      name: homebrew-tap
    homepage: "https://github.com/olga-safonova/miro-developer-platform-pp-cli"
    description: "<img src=\"https://content.pstmn.io/47449ea6-0ef7-4af2-bac1-e58a70e61c58/aW1hZ2UucG5n\" width=\"1685\" height=\"593\"> ###..."
    install: |
      bin.install "miro-developer-platform-pp-cli"
      bin.install "miro-developer-platform-pp-mcp"
