// Copyright 2026 olga-safonova. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newBoardsFramesCreateItemCmd(flags *rootFlags) *cobra.Command {
	var bodyData string
	var bodyGeometry string
	var bodyPosition string
	var bodyStyle string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "create-item <board_id>",
		Aliases:     []string{"create"},
		Short:       "Adds a frame to a board.<br/><h3>Required scope</h3> <a target=_blank...",
		Example:     "  miro-developer-platform-pp-cli boards frames create-item 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "frames.create-item", "pp:method": "POST", "pp:path": "/v2/boards/{board_id}/frames"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			if !stdinBody {
				if !cmd.Flags().Changed("data") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "data")
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/v2/boards/{board_id}/frames"
			path = replacePathParam(path, "board_id", args[0])
			var body any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				if err := json.Unmarshal(stdinData, &body); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
			} else {
				bodyFields := map[string]any{}
				if bodyData != "" {
					var parsedData any
					if err := json.Unmarshal([]byte(bodyData), &parsedData); err != nil {
						return fmt.Errorf("parsing --data JSON: %w", err)
					}
					bodyFields["data"] = parsedData
				}
				if bodyGeometry != "" {
					var parsedGeometry any
					if err := json.Unmarshal([]byte(bodyGeometry), &parsedGeometry); err != nil {
						return fmt.Errorf("parsing --geometry JSON: %w", err)
					}
					bodyFields["geometry"] = parsedGeometry
				}
				if bodyPosition != "" {
					var parsedPosition any
					if err := json.Unmarshal([]byte(bodyPosition), &parsedPosition); err != nil {
						return fmt.Errorf("parsing --position JSON: %w", err)
					}
					bodyFields["position"] = parsedPosition
				}
				if bodyStyle != "" {
					var parsedStyle any
					if err := json.Unmarshal([]byte(bodyStyle), &parsedStyle); err != nil {
						return fmt.Errorf("parsing --style JSON: %w", err)
					}
					bodyFields["style"] = parsedStyle
				}
				body = bodyFields
			}
			data, statusCode, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							return nil
						}
					}
				}
			}
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				if flags.quiet {
					return nil
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "frames",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300,
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				return printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true)
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&bodyData, "data", "", "Contains frame item data, such as the title, frame type, or frame format.")
	cmd.Flags().StringVar(&bodyGeometry, "geometry", "", "Contains geometrical information about the item, such as its width or height.")
	cmd.Flags().StringVar(&bodyPosition, "position", "", "Contains information about the item's position on the board, such as its `x` coordinate, `y` coordinate, and the...")
	cmd.Flags().StringVar(&bodyStyle, "style", "", "Contains information about the style of a frame item, such as the fill color.")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
