// Copyright 2026 olga-safonova. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newBoardsCreateCmd(flags *rootFlags) *cobra.Command {
	var bodyDescription string
	var bodyName string
	var bodyPolicy string
	var bodyProjectId string
	var bodyTeamId string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:   "create",
		Short: "Creates a board with the specified name and sharing policies.<br/><h4>Note</h4> You can only create up to 3 team...",
		Example: "  miro-developer-platform-pp-cli boards create",
		Annotations: map[string]string{"pp:endpoint": "boards.create", "pp:method": "POST", "pp:path": "/v2/boards"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !stdinBody {
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/v2/boards"
			var body any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				if err := json.Unmarshal(stdinData, &body); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
			} else {
				bodyFields := map[string]any{}
				if bodyDescription != "" {
					bodyFields["description"] = bodyDescription
				}
				if bodyName != "" {
					bodyFields["name"] = bodyName
				}
				if bodyPolicy != "" {
					var parsedPolicy any
					if err := json.Unmarshal([]byte(bodyPolicy), &parsedPolicy); err != nil {
						return fmt.Errorf("parsing --policy JSON: %w", err)
					}
					bodyFields["policy"] = parsedPolicy
				}
				if bodyProjectId != "" {
					bodyFields["projectId"] = bodyProjectId
				}
				if bodyTeamId != "" {
					bodyFields["teamId"] = bodyTeamId
				}
				body = bodyFields
			}
			data, statusCode, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						return nil
					}
				} else {
					var wrapped struct{ Data []map[string]any `json:"data"` }
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							return nil
						}
					}
				}
			}
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				if flags.quiet {
					return nil
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "boards",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300,
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				return printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true)
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&bodyDescription, "description", "", "Description of the board.")
	cmd.Flags().StringVar(&bodyName, "name", "Untitled", "Name for the board.")
	cmd.Flags().StringVar(&bodyPolicy, "policy", "", "Defines the permissions policies and sharing policies for the board.")
	cmd.Flags().StringVar(&bodyProjectId, "project-id", "", "Unique identifier (ID) of the project to which the board must be added. **Note**: Projects have been renamed to...")
	cmd.Flags().StringVar(&bodyTeamId, "team-id", "", "Unique identifier (ID) of the team where the board must be placed. **Note**: On Enterprise plan, boards can be moved...")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
