// Copyright 2026 olga-safonova. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newBoardsItemsAttachTagToCmd(flags *rootFlags) *cobra.Command {
	var flagTagId string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:   "attach-tag-to <board_id_PlatformTags> <item_id>",
		Short: "Attach an existing tag to the specified item. Card and sticky note items can have up to 8 tags....",
		Example: "  miro-developer-platform-pp-cli boards items attach-tag-to example-value 550e8400-e29b-41d4-a716-446655440000 --tag-id 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "items.attach-tag-to", "pp:method": "POST", "pp:path": "/v2/boards/{board_id_PlatformTags}/items/{item_id}"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			if !cmd.Flags().Changed("tag-id") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "tag-id")
			}
			if !stdinBody {
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/v2/boards/{board_id_PlatformTags}/items/{item_id}"
			path = replacePathParam(path, "board_id_PlatformTags", args[0])
			if len(args) < 2 {
				return usageErr(fmt.Errorf("item_id is required\nUsage: %s <%s>", cmd.CommandPath(), "item_id"))
			}
			path = replacePathParam(path, "item_id", args[1])
			queryParams := map[string]string{}
			if flagTagId != "" {
				queryParams["tag_id"] = fmt.Sprintf("%v", flagTagId)
			}
			var body any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				if err := json.Unmarshal(stdinData, &body); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
			} else {
				bodyFields := map[string]any{}
				body = bodyFields
			}
			data, statusCode, err := c.PostWithParams(path, queryParams, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						return nil
					}
				} else {
					var wrapped struct{ Data []map[string]any `json:"data"` }
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							return nil
						}
					}
				}
			}
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				if flags.quiet {
					return nil
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "items",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300,
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				return printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true)
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagTagId, "tag-id", "", "Unique identifier (ID) of the tag you want to add to the item.")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
