// Copyright 2026 olga-safonova. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newBoardsDocsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "docs",
		Short: "Manage docs",
	}

	cmd.AddCommand(newBoardsDocsCreateFormatItemCmd(flags))
	cmd.AddCommand(newBoardsDocsDeleteFormatItemCmd(flags))
	cmd.AddCommand(newBoardsDocsGetFormatItemCmd(flags))
	return cmd
}
