// Copyright 2026 olga-safonova. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newBoardsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "boards",
		Short: "Manage boards",
	}

	cmd.AddCommand(newBoardsCopyCmd(flags))
	cmd.AddCommand(newBoardsCreateCmd(flags))
	cmd.AddCommand(newBoardsDeleteCmd(flags))
	cmd.AddCommand(newBoardsGetCmd(flags))
	cmd.AddCommand(newBoardsGetSpecificCmd(flags))
	cmd.AddCommand(newBoardsUpdateCmd(flags))
	cmd.AddCommand(newBoardsAppCardsCmd(flags))
	cmd.AddCommand(newBoardsCardsCmd(flags))
	cmd.AddCommand(newBoardsConnectorsCmd(flags))
	cmd.AddCommand(newBoardsDocsCmd(flags))
	cmd.AddCommand(newBoardsDocumentsCmd(flags))
	cmd.AddCommand(newBoardsEmbedsCmd(flags))
	cmd.AddCommand(newBoardsFramesCmd(flags))
	cmd.AddCommand(newBoardsGroupsCmd(flags))
	cmd.AddCommand(newBoardsImagesCmd(flags))
	cmd.AddCommand(newBoardsItemsCmd(flags))
	cmd.AddCommand(newBoardsMembersCmd(flags))
	cmd.AddCommand(newBoardsShapesCmd(flags))
	cmd.AddCommand(newBoardsStickyNotesCmd(flags))
	cmd.AddCommand(newBoardsTagsCmd(flags))
	cmd.AddCommand(newBoardsTextsCmd(flags))
	return cmd
}
