// Copyright 2026 olga-safonova. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newBoardsDocumentsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "documents",
		Short: "Manage documents",
	}

	cmd.AddCommand(newBoardsDocumentsCreateItemUsingFileFromDeviceCmd(flags))
	cmd.AddCommand(newBoardsDocumentsCreateItemUsingUrlCmd(flags))
	cmd.AddCommand(newBoardsDocumentsDeleteItemCmd(flags))
	cmd.AddCommand(newBoardsDocumentsGetItemCmd(flags))
	cmd.AddCommand(newBoardsDocumentsUpdateItemUsingFileFromDeviceCmd(flags))
	cmd.AddCommand(newBoardsDocumentsUpdateItemUsingUrlCmd(flags))
	return cmd
}
