// Copyright 2026 olga-safonova. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newBoardsGroupsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "groups",
		Short: "Manage groups",
	}

	cmd.AddCommand(newBoardsGroupsCreateCmd(flags))
	cmd.AddCommand(newBoardsGroupsDeleteCmd(flags))
	cmd.AddCommand(newBoardsGroupsGetAllCmd(flags))
	cmd.AddCommand(newBoardsGroupsGetByIdCmd(flags))
	cmd.AddCommand(newBoardsGroupsGetItemsByIdCmd(flags))
	cmd.AddCommand(newBoardsGroupsUnCmd(flags))
	cmd.AddCommand(newBoardsGroupsUpdateCmd(flags))
	return cmd
}
