// Copyright 2026 olga-safonova. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newBoardsConnectorsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "connectors",
		Short: "Manage connectors",
	}

	cmd.AddCommand(newBoardsConnectorsCreateCmd(flags))
	cmd.AddCommand(newBoardsConnectorsDeleteCmd(flags))
	cmd.AddCommand(newBoardsConnectorsGetCmd(flags))
	cmd.AddCommand(newBoardsConnectorsGetBoardsCmd(flags))
	cmd.AddCommand(newBoardsConnectorsUpdateCmd(flags))
	return cmd
}
