// Copyright 2026 olga-safonova. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newBoardsTextsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "texts",
		Short: "Manage texts",
	}

	cmd.AddCommand(newBoardsTextsCreateItemCmd(flags))
	cmd.AddCommand(newBoardsTextsDeleteItemCmd(flags))
	cmd.AddCommand(newBoardsTextsGetItemCmd(flags))
	cmd.AddCommand(newBoardsTextsUpdateItemCmd(flags))
	return cmd
}
