// Copyright 2026 olga-safonova. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newBoardsStickyNotesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "sticky-notes",
		Short: "Manage sticky notes",
	}

	cmd.AddCommand(newBoardsStickyNotesCreateItemCmd(flags))
	cmd.AddCommand(newBoardsStickyNotesDeleteItemCmd(flags))
	cmd.AddCommand(newBoardsStickyNotesGetItemCmd(flags))
	cmd.AddCommand(newBoardsStickyNotesUpdateItemCmd(flags))
	return cmd
}
