// Copyright 2026 olga-safonova. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newBoardsItemsGetWithinFrameCmd(flags *rootFlags) *cobra.Command {
	var flagParentItemId string
	var flagLimit string
	var flagType string
	var flagCursor string
	var flagAll bool

	cmd := &cobra.Command{
		Use:         "get-within-frame <board_id_PlatformContainers>",
		Short:       "Retrieves a list of items within a specific frame. A frame is a parent item and all items within a frame are child...",
		Example:     "  miro-developer-platform-pp-cli boards items get-within-frame example-value --parent-item-id 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "items.get-within-frame", "pp:method": "GET", "pp:path": "/v2/boards/{board_id_PlatformContainers}/items", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			if !cmd.Flags().Changed("parent-item-id") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "parent-item-id")
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/v2/boards/{board_id_PlatformContainers}/items"
			path = replacePathParam(path, "board_id_PlatformContainers", args[0])
			data, prov, err := resolvePaginatedRead(cmd.Context(), c, flags, "items", path, map[string]string{
				"parent_item_id": fmt.Sprintf("%v", flagParentItemId),
				"limit":          fmt.Sprintf("%v", flagLimit),
				"type":           fmt.Sprintf("%v", flagType),
				"cursor":         fmt.Sprintf("%v", flagCursor),
			}, nil, flagAll, "cursor", "", "")
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Unwrap single-key array-wrapper responses (e.g. {"tags":[...]},
			// {"items":[...]}) so the count, table, and provenance envelope all
			// see the inner list. Multi-key wrappers (paginated lists with
			// cursor/total fields) pass through unchanged.
			data = unwrapListResponse(data)
			// Print provenance to stderr for human-facing output
			{
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested.
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagParentItemId, "parent-item-id", "", "ID of the frame for which you want to retrieve the list of available items.")
	cmd.Flags().StringVar(&flagLimit, "limit", "10", "Limit")
	cmd.Flags().StringVar(&flagType, "type", "", "Type")
	cmd.Flags().StringVar(&flagCursor, "cursor", "", "Cursor")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	return cmd
}
