// Copyright 2026 olga-safonova. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newBoardsGetCmd(flags *rootFlags) *cobra.Command {
	var flagTeamId string
	var flagProjectId string
	var flagQuery string
	var flagOwner string
	var flagLimit string
	var flagOffset string
	var flagSort string
	var flagAll bool

	cmd := &cobra.Command{
		Use:         "get",
		Aliases:     []string{"list"},
		Short:       "Retrieves a list of boards accessible to the user associated with the provided access token. This endpoint supports...",
		Example:     "  miro-cli boards get",
		Annotations: map[string]string{"pp:endpoint": "boards.get", "pp:method": "GET", "pp:path": "/v2/boards", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if cmd.Flags().Changed("sort") {
				allowedSort := []string{"default", "last_modified", "last_opened", "last_created", "alphabetically"}
				validSort := false
				for _, v := range allowedSort {
					if flagSort == v {
						validSort = true
						break
					}
				}
				if !validSort {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "sort", flagSort, allowedSort)
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/v2/boards"
			data, prov, err := resolvePaginatedRead(cmd.Context(), c, flags, "boards", path, map[string]string{
				"team_id":    fmt.Sprintf("%v", flagTeamId),
				"project_id": fmt.Sprintf("%v", flagProjectId),
				"query":      fmt.Sprintf("%v", flagQuery),
				"owner":      fmt.Sprintf("%v", flagOwner),
				"limit":      fmt.Sprintf("%v", flagLimit),
				"offset":     fmt.Sprintf("%v", flagOffset),
				"sort":       fmt.Sprintf("%v", flagSort),
			}, nil, flagAll, "offset", "", "")
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Unwrap single-key array-wrapper responses (e.g. {"tags":[...]},
			// {"items":[...]}) so the count, table, and provenance envelope all
			// see the inner list. Multi-key wrappers (paginated lists with
			// cursor/total fields) pass through unchanged.
			data = unwrapListResponse(data)
			// Print provenance to stderr for human-facing output
			{
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested.
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagTeamId, "team-id", "", "Team id")
	cmd.Flags().StringVar(&flagProjectId, "project-id", "", "Project id")
	cmd.Flags().StringVar(&flagQuery, "query", "", "Query")
	cmd.Flags().StringVar(&flagOwner, "owner", "", "Owner")
	cmd.Flags().StringVar(&flagLimit, "limit", "", "Limit")
	cmd.Flags().StringVar(&flagOffset, "offset", "", "Offset")
	cmd.Flags().StringVar(&flagSort, "sort", "default", "Sort (one of: default, last_modified, last_opened, last_created, alphabetically)")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	return cmd
}
