// Copyright 2026 olga-safonova. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newBoardsItemsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "items",
		Short: "Manage items",
	}

	cmd.AddCommand(newBoardsItemsAttachTagToCmd(flags))
	cmd.AddCommand(newBoardsItemsCreateCmd(flags))
	cmd.AddCommand(newBoardsItemsCreateInBulkUsingFileFromDeviceCmd(flags))
	cmd.AddCommand(newBoardsItemsDeleteCmd(flags))
	cmd.AddCommand(newBoardsItemsGetCmd(flags))
	cmd.AddCommand(newBoardsItemsGetByTagCmd(flags))
	cmd.AddCommand(newBoardsItemsGetSpecificCmd(flags))
	cmd.AddCommand(newBoardsItemsGetTagsFromCmd(flags))
	cmd.AddCommand(newBoardsItemsGetWithinFrameCmd(flags))
	cmd.AddCommand(newBoardsItemsRemoveTagFromCmd(flags))
	cmd.AddCommand(newBoardsItemsUpdatePositionOrParentCmd(flags))
	return cmd
}
