// Copyright 2026 olga-safonova. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newBoardsImagesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "images",
		Short: "Manage images",
	}

	cmd.AddCommand(newBoardsImagesCreateItemUsingLocalFileCmd(flags))
	cmd.AddCommand(newBoardsImagesCreateItemUsingUrlCmd(flags))
	cmd.AddCommand(newBoardsImagesDeleteItemCmd(flags))
	cmd.AddCommand(newBoardsImagesGetItemCmd(flags))
	cmd.AddCommand(newBoardsImagesUpdateItemUsingFileFromDeviceCmd(flags))
	cmd.AddCommand(newBoardsImagesUpdateItemUsingUrlCmd(flags))
	return cmd
}
