// Copyright 2026 olga-safonova. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newBoardsEmbedsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "embeds",
		Short: "Manage embeds",
	}

	cmd.AddCommand(newBoardsEmbedsCreateItemCmd(flags))
	cmd.AddCommand(newBoardsEmbedsDeleteItemCmd(flags))
	cmd.AddCommand(newBoardsEmbedsGetItemCmd(flags))
	cmd.AddCommand(newBoardsEmbedsUpdateItemCmd(flags))
	return cmd
}
