// Copyright 2026 olga-safonova. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newBoardsCardsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "cards",
		Short: "Manage cards",
	}

	cmd.AddCommand(newBoardsCardsCreateItemCmd(flags))
	cmd.AddCommand(newBoardsCardsDeleteItemCmd(flags))
	cmd.AddCommand(newBoardsCardsGetItemCmd(flags))
	cmd.AddCommand(newBoardsCardsUpdateItemCmd(flags))
	return cmd
}
