// Copyright 2026 olga-safonova. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newBoardsTagsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "tags",
		Short: "Manage tags",
	}

	cmd.AddCommand(newBoardsTagsCreateCmd(flags))
	cmd.AddCommand(newBoardsTagsDeleteCmd(flags))
	cmd.AddCommand(newBoardsTagsGetCmd(flags))
	cmd.AddCommand(newBoardsTagsGetFromBoardCmd(flags))
	cmd.AddCommand(newBoardsTagsUpdateCmd(flags))
	return cmd
}
