// Copyright 2026 olga-safonova. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newBoardsConnectorsUpdateCmd(flags *rootFlags) *cobra.Command {
	var bodyCaptions string
	var bodyEndItem string
	var bodyShape string
	var bodyStartItem string
	var bodyStyle string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:   "update <board_id> <connector_id>",
		Short: "Updates a connector on a board based on the data and style properties provided in the request body.<br/><h3>Required...",
		Example: "  miro-developer-platform-pp-cli boards connectors update 550e8400-e29b-41d4-a716-446655440000 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "connectors.update", "pp:method": "PATCH", "pp:path": "/v2/boards/{board_id}/connectors/{connector_id}"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			if !stdinBody {
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/v2/boards/{board_id}/connectors/{connector_id}"
			path = replacePathParam(path, "board_id", args[0])
			if len(args) < 2 {
				return usageErr(fmt.Errorf("connector_id is required\nUsage: %s <%s>", cmd.CommandPath(), "connector_id"))
			}
			path = replacePathParam(path, "connector_id", args[1])
			var body any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				if err := json.Unmarshal(stdinData, &body); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
			} else {
				bodyFields := map[string]any{}
				if bodyCaptions != "" {
					var parsedCaptions any
					if err := json.Unmarshal([]byte(bodyCaptions), &parsedCaptions); err != nil {
						return fmt.Errorf("parsing --captions JSON: %w", err)
					}
					bodyFields["captions"] = parsedCaptions
				}
				if bodyEndItem != "" {
					var parsedEndItem any
					if err := json.Unmarshal([]byte(bodyEndItem), &parsedEndItem); err != nil {
						return fmt.Errorf("parsing --end-item JSON: %w", err)
					}
					bodyFields["endItem"] = parsedEndItem
				}
				if bodyShape != "" {
					bodyFields["shape"] = bodyShape
				}
				if bodyStartItem != "" {
					var parsedStartItem any
					if err := json.Unmarshal([]byte(bodyStartItem), &parsedStartItem); err != nil {
						return fmt.Errorf("parsing --start-item JSON: %w", err)
					}
					bodyFields["startItem"] = parsedStartItem
				}
				if bodyStyle != "" {
					var parsedStyle any
					if err := json.Unmarshal([]byte(bodyStyle), &parsedStyle); err != nil {
						return fmt.Errorf("parsing --style JSON: %w", err)
					}
					bodyFields["style"] = parsedStyle
				}
				body = bodyFields
			}
			data, statusCode, err := c.Patch(path, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						return nil
					}
				} else {
					var wrapped struct{ Data []map[string]any `json:"data"` }
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							return nil
						}
					}
				}
			}
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				if flags.quiet {
					return nil
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				envelope := map[string]any{
					"action":   "patch",
					"resource": "connectors",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300,
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				return printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true)
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&bodyCaptions, "captions", "", "Blocks of text you want to display on the connector.")
	cmd.Flags().StringVar(&bodyEndItem, "end-item", "", "The ending point of the connector. If startItem is also provided, endItem.id must be different from startItem.id")
	cmd.Flags().StringVar(&bodyShape, "shape", "", "The path type of the connector line, defines curvature. Default: curved.")
	cmd.Flags().StringVar(&bodyStartItem, "start-item", "", "The ending point of the connector. If startItem is also provided, endItem.id must be different from startItem.id")
	cmd.Flags().StringVar(&bodyStyle, "style", "", "Contains information about the style of a connector, such as the color or caption font size")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
