// Copyright 2026 olga-safonova. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newBoardsShapesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "shapes",
		Short: "Manage shapes",
	}

	cmd.AddCommand(newBoardsShapesCreateItemCmd(flags))
	cmd.AddCommand(newBoardsShapesDeleteItemCmd(flags))
	cmd.AddCommand(newBoardsShapesGetItemCmd(flags))
	cmd.AddCommand(newBoardsShapesUpdateItemCmd(flags))
	return cmd
}
