// Copyright 2026 olga-safonova. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newBoardsDocsGetFormatItemCmd(flags *rootFlags) *cobra.Command {
	var flagTextContentType string

	cmd := &cobra.Command{
		Use:         "get-format-item <board_id> <item_id>",
		Aliases:     []string{"get"},
		Short:       "Retrieves information for a specific doc format item on a board.<br/><h3>Required scope</h3> <a target=_blank...",
		Example:     "  miro-developer-platform-pp-cli boards docs get-format-item 550e8400-e29b-41d4-a716-446655440000 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "docs.get-format-item", "pp:method": "GET", "pp:path": "/v2/boards/{board_id}/docs/{item_id}", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			if cmd.Flags().Changed("text-content-type") {
				allowedTextContentType := []string{"html", "markdown"}
				validTextContentType := false
				for _, v := range allowedTextContentType {
					if flagTextContentType == v {
						validTextContentType = true
						break
					}
				}
				if !validTextContentType {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "text-content-type", flagTextContentType, allowedTextContentType)
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/v2/boards/{board_id}/docs/{item_id}"
			path = replacePathParam(path, "board_id", args[0])
			if len(args) < 2 {
				return usageErr(fmt.Errorf("item_id is required\nUsage: %s <%s>", cmd.CommandPath(), "item_id"))
			}
			path = replacePathParam(path, "item_id", args[1])
			params := map[string]string{}
			if flagTextContentType != "" {
				params["textContentType"] = fmt.Sprintf("%v", flagTextContentType)
			}
			data, prov, err := resolveRead(cmd.Context(), c, flags, "docs", false, path, params, nil)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Unwrap single-key array-wrapper responses (e.g. {"tags":[...]},
			// {"items":[...]}) so the count, table, and provenance envelope all
			// see the inner list. Multi-key wrappers (paginated lists with
			// cursor/total fields) pass through unchanged.
			data = unwrapListResponse(data)
			// Print provenance to stderr for human-facing output
			{
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested.
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagTextContentType, "text-content-type", "", "Controls the contentType of the returned doc's content. (one of: html, markdown)")

	return cmd
}
