// Copyright 2026 olga-safonova. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newBoardsFramesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "frames",
		Short: "Manage frames",
	}

	cmd.AddCommand(newBoardsFramesCreateItemCmd(flags))
	cmd.AddCommand(newBoardsFramesDeleteItemCmd(flags))
	cmd.AddCommand(newBoardsFramesGetItemCmd(flags))
	cmd.AddCommand(newBoardsFramesUpdateItemCmd(flags))
	return cmd
}
