// Copyright 2026 olga-safonova. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newBoardsAppCardsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "app-cards",
		Short: "Manage app cards",
	}

	cmd.AddCommand(newBoardsAppCardsCreateItemCmd(flags))
	cmd.AddCommand(newBoardsAppCardsDeleteItemCmd(flags))
	cmd.AddCommand(newBoardsAppCardsGetItemCmd(flags))
	cmd.AddCommand(newBoardsAppCardsUpdateItemCmd(flags))
	return cmd
}
