// Copyright 2026 olga-safonova. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newBoardsMembersCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "members",
		Short: "Manage members",
	}

	cmd.AddCommand(newBoardsMembersGetBoardCmd(flags))
	cmd.AddCommand(newBoardsMembersGetSpecificBoardCmd(flags))
	cmd.AddCommand(newBoardsMembersRemoveBoardCmd(flags))
	cmd.AddCommand(newBoardsMembersShareBoardCmd(flags))
	cmd.AddCommand(newBoardsMembersUpdateBoardCmd(flags))
	return cmd
}
