// Copyright 2026 olga-safonova. Licensed under Apache-2.0. See LICENSE.
//
// Hand-authored — extracted from helpers.go during the cohesion-split
// refactor. Do not re-add the "Generated by CLI Printing Press" marker;
// the regenmerge pass uses that marker to decide what to clobber.
//
// Responsibility: filter, compact, and unwrap JSON responses before they
// reach the renderers. Includes:
//   - --select dotted-path filtering
//   - --compact allow/blocklist field stripping
//   - single-key array-wrapper unwrapping (for {tags: [...]} shape responses)
//   - status-envelope unwrapping (for {status:"success", data:[...]} shape)

package cli

import (
	"bytes"
	"encoding/json"
	"strings"
	"unicode"
)

// filterFields keeps only the specified fields (comma-separated) from JSON objects/arrays.
// Supports dotted paths like "events.shortName" to descend into nested structures.
// Arrays are traversed element-wise: "events.shortName" keeps shortName on each event.
func filterFields(data json.RawMessage, fields string) json.RawMessage {
	paths := parseFieldPaths(fields)
	if len(paths) == 0 {
		return data
	}
	return filterFieldsRec(data, paths)
}

func parseFieldPaths(fields string) [][]string {
	var paths [][]string
	for _, f := range strings.Split(fields, ",") {
		f = strings.TrimSpace(f)
		if f == "" {
			continue
		}
		parts := strings.Split(f, ".")
		for i := range parts {
			parts[i] = strings.ToLower(parts[i])
		}
		paths = append(paths, parts)
	}
	return paths
}

// filterFieldsRec applies path filters to a JSON value. Each path is a list of
// lowercase segments; arrays descend element-wise.
func filterFieldsRec(data json.RawMessage, paths [][]string) json.RawMessage {
	if arr, ok := tryUnmarshalArray(data); ok {
		out := make([]json.RawMessage, len(arr))
		for i, el := range arr {
			out[i] = filterFieldsRec(el, paths)
		}
		result, _ := json.Marshal(out)
		return result
	}
	if obj, ok := tryUnmarshalObject(data); ok {
		return filterObject(obj, paths)
	}
	return data
}

func tryUnmarshalArray(data json.RawMessage) ([]json.RawMessage, bool) {
	var arr []json.RawMessage
	if err := json.Unmarshal(data, &arr); err != nil {
		return nil, false
	}
	return arr, true
}

func tryUnmarshalObject(data json.RawMessage) (map[string]json.RawMessage, bool) {
	var obj map[string]json.RawMessage
	if err := json.Unmarshal(data, &obj); err != nil {
		return nil, false
	}
	return obj, true
}

func filterObject(obj map[string]json.RawMessage, paths [][]string) json.RawMessage {
	keepWhole, subPaths := splitFieldPaths(paths)
	filtered := map[string]json.RawMessage{}
	for k, v := range obj {
		matched := matchSelectSegment(k, keepWhole, subPaths)
		if matched == "" {
			continue
		}
		if keepWhole[matched] {
			filtered[k] = v
			continue
		}
		if subs := subPaths[matched]; subs != nil {
			filtered[k] = filterFieldsRec(v, subs)
		}
	}
	result, _ := json.Marshal(filtered)
	return result
}

func splitFieldPaths(paths [][]string) (map[string]bool, map[string][][]string) {
	keepWhole := map[string]bool{}
	subPaths := map[string][][]string{}
	for _, p := range paths {
		if len(p) == 0 {
			continue
		}
		head := p[0]
		if len(p) == 1 {
			keepWhole[head] = true
			continue
		}
		subPaths[head] = append(subPaths[head], p[1:])
	}
	return keepWhole, subPaths
}

// matchSelectSegment returns the matching lowercase segment, or "" if no match.
// Supports direct case-insensitive match and camelCase→kebab-case conversion.
func matchSelectSegment(fieldName string, keepWhole map[string]bool, subPaths map[string][][]string) string {
	lower := strings.ToLower(fieldName)
	if keepWhole[lower] || subPaths[lower] != nil {
		return lower
	}
	kebab := camelToKebab(fieldName)
	if kebab != lower && (keepWhole[kebab] || subPaths[kebab] != nil) {
		return kebab
	}
	return ""
}

// camelToKebab converts "orderDate" or "orderdate" to "order-date" by splitting on
// uppercase boundaries. For already-lowercase input, splits on known word boundaries.
func camelToKebab(s string) string {
	var b strings.Builder
	runes := []rune(s)
	for i, r := range runes {
		if i > 0 && unicode.IsUpper(r) && unicode.IsLower(runes[i-1]) {
			b.WriteByte('-')
		}
		b.WriteRune(unicode.ToLower(r))
	}
	return b.String()
}

// rawAtPath descends a dotted path through a JSON object and returns the raw
// value at the leaf, or false if any segment is missing.
func rawAtPath(obj map[string]json.RawMessage, path string) (json.RawMessage, bool) {
	if raw, ok := obj[path]; ok {
		return raw, true
	}
	current := obj
	parts := strings.Split(path, ".")
	for i, part := range parts {
		raw, ok := current[part]
		if !ok {
			return nil, false
		}
		if i == len(parts)-1 {
			return raw, true
		}
		if err := json.Unmarshal(raw, &current); err != nil {
			return nil, false
		}
	}
	return nil, false
}

// unwrapListResponse unwraps single-key array-wrapper responses so that
// downstream count/render code sees the inner list. Many REST APIs return
// list resources wrapped in a single-property object — `{tags: [...]}`,
// `{items: [...]}`, `{results: [...]}`, etc. — and the spec parser
// currently special-cases only the `{data: [...]}` shape. Without this
// unwrap, table render and item-count logic silently treat any other
// wrapper key as "zero items".
//
// Conservative: fires only when the response is an object with exactly
// one property whose value is a JSON array. Multi-key wrapper responses
// (paginated lists with cursor/total fields) intentionally pass through
// unchanged so consumers can still read the pagination metadata.
func unwrapListResponse(data json.RawMessage) json.RawMessage {
	trimmed := bytes.TrimSpace(data)
	if len(trimmed) == 0 || trimmed[0] != '{' {
		return data
	}
	var obj map[string]json.RawMessage
	if err := json.Unmarshal(data, &obj); err != nil || len(obj) != 1 {
		return data
	}
	for _, value := range obj {
		v := bytes.TrimSpace(value)
		if len(v) > 0 && v[0] == '[' {
			return value
		}
	}
	return data
}

// extractResponseData unwraps common API response envelopes for display.
// Many APIs return {"status":"success","data":[...]} instead of a bare array.
// This extracts the inner data for output helpers (filterFields, compactFields,
// the table renderer) that expect arrays or flat objects.
//
// Only unwraps when a "status" field is present and indicates success — this
// avoids false positives on APIs where "data" is a regular field (e.g., Stripe
// returns {"data":[...],"has_more":true} where "data" is the list, not an
// envelope wrapper).
func extractResponseData(data json.RawMessage) json.RawMessage {
	var envelope struct {
		Status string          `json:"status"`
		Data   json.RawMessage `json:"data"`
	}
	if err := json.Unmarshal(data, &envelope); err != nil {
		return data
	}
	if envelope.Data == nil || envelope.Status == "" {
		return data
	}
	switch envelope.Status {
	case "success", "ok", "OK", "Success":
		return envelope.Data
	}
	return data
}

// compactFields keeps only the most important fields for agent consumption.
// For arrays: allowlist of high-gravity fields (no descriptions).
// For single objects: blocklist that strips known-verbose fields (descriptions, comments, etc.).
func compactFields(data json.RawMessage) json.RawMessage {
	var items []map[string]any
	if err := json.Unmarshal(data, &items); err == nil {
		return compactListFields(items)
	}
	var obj map[string]any
	if err := json.Unmarshal(data, &obj); err == nil {
		return compactObjectFields(obj)
	}
	return data
}

// compactListKeepFields is the allowlist of high-gravity fields kept in array
// responses when --compact is set. Defined at package scope so it can be
// extended without touching the function body.
var compactListKeepFields = map[string]bool{
	"id": true, "name": true, "title": true, "identifier": true,
	"status": true, "state": true, "type": true, "priority": true,
	"url": true, "email": true, "key": true,
	"created_at": true, "updated_at": true, "createdAt": true, "updatedAt": true,
}

// compactObjectStripFields is the blocklist of verbose fields stripped from
// single-object responses when --compact is set.
var compactObjectStripFields = map[string]bool{
	"description": true, "body": true, "content": true,
	"comments": true, "attachments": true, "html": true, "markdown": true,
}

// compactListFields keeps only high-gravity fields for array responses.
func compactListFields(items []map[string]any) json.RawMessage {
	filtered := make([]map[string]any, 0, len(items))
	for _, item := range items {
		compact := map[string]any{}
		for k, v := range item {
			if compactListKeepFields[k] {
				compact[k] = v
			}
		}
		filtered = append(filtered, compact)
	}
	result, _ := json.Marshal(filtered)
	return result
}

// compactObjectFields strips known-verbose fields from single-object responses.
// Uses a blocklist so it works across all API domains (project management, payments, CRM, etc.).
func compactObjectFields(obj map[string]any) json.RawMessage {
	compact := map[string]any{}
	for k, v := range obj {
		if !compactObjectStripFields[k] {
			compact[k] = v
		}
	}
	result, _ := json.Marshal(compact)
	return result
}
