// Copyright 2026 olga-safonova. Licensed under Apache-2.0. See LICENSE.
//
// Hand-authored after the cohesion-split refactor. The original generated
// file was 1,280 lines doing many unrelated things (table render, CSV,
// field filtering, pagination, error classification, provenance). It has
// been split into render_table.go, render_csv.go, filter_fields.go, and
// pagination.go. What remains here is the core that did NOT move:
//
//   - color/TTY detection
//   - cliError exit-code wrappers
//   - dry-run / sync-warning classification
//   - classifyAPIError / classifyDeleteError
//   - small primitives (truncate, replacePathParam)
//   - the JSON output pipeline entry points (printJSONFiltered,
//     printOutputWithFlags, printOutput)
//   - the suggest-flag / Levenshtein helper
//   - DataProvenance + printProvenance + wrapWithProvenance
//   - defaultDBPath
//
// IMPORTANT: the "Generated by CLI Printing Press" marker has been
// removed deliberately. The regenmerge pass uses that marker to decide
// what to clobber on regen; without it, this file is treated as
// hand-authored and preserved. Adding the marker back would cause the
// next regen to restore the full original 1,280-line shape, producing
// duplicate definitions against the four sibling files.

package cli

import (
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"time"

	"miro-cli/internal/client"
	"miro-cli/internal/cliutil"

	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
)

var As = errors.As

// noColor is set by the --no-color flag.
var noColor bool

// humanFriendly is set by the --human-friendly flag; colors are off by default
// (agent-safe).
var humanFriendly bool

func colorEnabled() bool {
	if noColor || !humanFriendly {
		return false
	}
	if os.Getenv("NO_COLOR") != "" {
		return false
	}
	if os.Getenv("TERM") == "dumb" {
		return false
	}
	return isTerminal(os.Stdout)
}

func isTerminal(w io.Writer) bool {
	f, ok := w.(*os.File)
	if !ok {
		return false
	}
	fi, err := f.Stat()
	if err != nil {
		return true
	}
	return (fi.Mode() & os.ModeCharDevice) != 0
}

func bold(s string) string {
	if !colorEnabled() {
		return s
	}
	return "\033[1m" + s + "\033[0m"
}

func green(s string) string {
	if !colorEnabled() {
		return s
	}
	return "\033[32m" + s + "\033[0m"
}

func red(s string) string {
	if !colorEnabled() {
		return s
	}
	return "\033[31m" + s + "\033[0m"
}

func yellow(s string) string {
	if !colorEnabled() {
		return s
	}
	return "\033[33m" + s + "\033[0m"
}

type cliError struct {
	code int
	err  error
}

func (e *cliError) Error() string { return e.err.Error() }
func (e *cliError) Unwrap() error { return e.err }

func usageErr(err error) error     { return &cliError{code: 2, err: err} }
func notFoundErr(err error) error  { return &cliError{code: 3, err: err} }
func authErr(err error) error      { return &cliError{code: 4, err: err} }
func apiErr(err error) error       { return &cliError{code: 5, err: err} }
func configErr(err error) error    { return &cliError{code: 10, err: err} }
func rateLimitErr(err error) error { return &cliError{code: 7, err: err} }

// dryRunOK reports whether the command should short-circuit without doing any
// real work because --dry-run was set. The verify pipeline probes hand-written
// commands with --dry-run; commands that put validation in cobra's `Args:` or
// `MarkFlagRequired` cannot reach a dry-run guard inside RunE because cobra
// runs those checks before RunE. The verify-friendly pattern for hand-written
// commands is:
//
//	RunE: func(cmd *cobra.Command, args []string) error {
//	    if len(args) == 0 {
//	        return cmd.Help()
//	    }
//	    if dryRunOK(flags) {
//	        return nil
//	    }
//	    // ... real work ...
//	}
//
// See SKILL.md "Phase 3: Build The GOAT" for the full pattern.
func dryRunOK(flags *rootFlags) bool {
	return flags != nil && flags.dryRun
}

// accessWarning describes an API access-denial that sync converts into a
// non-fatal warning. It carries enough structured data for the sync_warning
// JSON event without parsing free-form error strings downstream.
type accessWarning struct {
	Status  int    // HTTP status when applicable; 0 for GraphQL field-level denials.
	Reason  string // "forbidden" | "insufficient_access" | "unauthenticated"
	Message string // human-readable detail (the API's body or GraphQL error message)
}

// accessDenialPatterns matches API error bodies that indicate the request was
// rejected for access-policy reasons rather than for input validity.
var accessDenialPatterns = []*regexp.Regexp{
	regexp.MustCompile(`\bforbidden\b`),
	regexp.MustCompile(`\bunauthorized\b`),
	regexp.MustCompile(`\bnot[\s_-]?authorized\b`),
	regexp.MustCompile(`\bpermission[\s_-]?denied\b`),
	regexp.MustCompile(`\baccess[\s_-]?denied\b`),
	regexp.MustCompile(`\binsufficient[\s_-]?(scope|permission|privilege)`),
	regexp.MustCompile(`\binvalid[\s_-]?scope\b`),
	regexp.MustCompile(`\bmissing[\s_-]?scope\b`),
	regexp.MustCompile(`\brequires?\s+(elevated|admin|enterprise|business|workspace|enterprise[\s_-]?tier)`),
}

// looksLikeAccessDenial reports whether body text describes an access-policy
// rejection. Use it on response-body content (apiErr.Body), not on the full
// error string — the request path can contain words like "auth" or "tokens"
// that would produce false positives if the whole error message were scanned.
func looksLikeAccessDenial(body string) bool {
	lower := strings.ToLower(body)
	for _, p := range accessDenialPatterns {
		if p.MatchString(lower) {
			return true
		}
	}
	return false
}

// isSyncAccessWarning classifies err as an access-denial warning suitable for
// sync's warn-and-continue path. It returns nil, false for any error that
// should remain a hard sync failure: HTTP 401 (token-level auth failure
// requiring re-auth), 5xx, network errors, and HTTP 400 responses whose
// bodies do not match an access-policy pattern.
func isSyncAccessWarning(err error) (*accessWarning, bool) {
	if err == nil {
		return nil, false
	}
	var apiErr *client.APIError
	if !errors.As(err, &apiErr) {
		return nil, false
	}
	switch apiErr.StatusCode {
	case 403:
		return &accessWarning{Status: 403, Reason: "forbidden", Message: apiErr.Body}, true
	case 400:
		if looksLikeAccessDenial(apiErr.Body) {
			return &accessWarning{Status: 400, Reason: "insufficient_access", Message: apiErr.Body}, true
		}
	}
	return nil, false
}

type noopResult struct {
	Status string `json:"status"`
	Reason string `json:"reason"`
}

func writeNoop(flags *rootFlags, reason, prose string) error {
	if flags != nil && flags.asJSON {
		return json.NewEncoder(os.Stdout).Encode(noopResult{Status: "noop", Reason: reason})
	}
	fmt.Fprintln(os.Stderr, prose)
	return nil
}

func writeAPIErrorEnvelope(flags *rootFlags, err error, code int) {
	if flags == nil || !flags.asJSON {
		return
	}
	_ = json.NewEncoder(os.Stdout).Encode(map[string]any{
		"error": err.Error(),
		"code":  code,
	})
}

// classifyAPIError maps API errors to structured exit codes with actionable hints.
// Dispatches via a table to keep the function flat; the table maps the HTTP
// status fragment to a (matcher, classifier) pair.
func classifyAPIError(err error, flags *rootFlags) error {
	msg := err.Error()
	for _, c := range apiErrorClassifiers {
		if c.matches(msg) {
			return c.classify(err, msg, flags)
		}
	}
	return apiErr(err)
}

type apiErrorClassifier struct {
	matches  func(msg string) bool
	classify func(err error, msg string, flags *rootFlags) error
}

var apiErrorClassifiers = []apiErrorClassifier{
	{
		matches: func(msg string) bool { return strings.Contains(msg, "HTTP 409") },
		classify: func(err error, _ string, flags *rootFlags) error {
			if flags != nil && flags.idempotent {
				return writeNoop(flags, "already_exists", "already exists (no-op)")
			}
			classified := apiErr(err)
			writeAPIErrorEnvelope(flags, classified, ExitCode(classified))
			return classified
		},
	},
	{
		matches: func(msg string) bool {
			return strings.Contains(msg, "HTTP 400") && cliutil.LooksLikeAuthError(msg)
		},
		classify: func(err error, msg string, _ *rootFlags) error {
			return authErr(fmt.Errorf("%w\nhint: the API rejected the request — this usually means auth is missing or invalid."+
				"\n      Set your API key: export MIRO_ACCESS_TOKEN=<your-key>"+
				"\n      Run 'miro-cli doctor' to check auth status."+
				"\n      Response: "+cliutil.SanitizeErrorBody(msg), err))
		},
	},
	{
		matches: func(msg string) bool { return strings.Contains(msg, "HTTP 401") },
		classify: func(err error, _ string, _ *rootFlags) error {
			return authErr(fmt.Errorf("%w\nhint: check your token. Set it with: miro-cli auth set-token <token>"+
				"\n      or: export MIRO_ACCESS_TOKEN=<your-token>"+
				"\n      Run 'miro-cli doctor' to check auth status.", err))
		},
	},
	{
		matches: func(msg string) bool { return strings.Contains(msg, "HTTP 403") },
		classify: func(err error, _ string, _ *rootFlags) error {
			return authErr(fmt.Errorf("%w\nhint: permission denied. Your credentials are valid but lack access to this resource."+
				"\n      Check that your API key has the required permissions."+
				"\n      Set it with: export MIRO_ACCESS_TOKEN=<your-key>"+
				"\n      Run 'miro-cli doctor' to check auth status.", err))
		},
	},
	{
		matches: func(msg string) bool { return strings.Contains(msg, "HTTP 404") },
		classify: func(err error, _ string, _ *rootFlags) error {
			return notFoundErr(fmt.Errorf("%w\nhint: resource not found. Run the 'list' command to see available items", err))
		},
	},
	{
		matches:  func(msg string) bool { return strings.Contains(msg, "HTTP 429") },
		classify: func(err error, _ string, _ *rootFlags) error { return rateLimitErr(err) },
	},
}

// classifyDeleteError maps DELETE errors and supports explicit idempotent no-op handling.
func classifyDeleteError(err error, flags *rootFlags) error {
	msg := err.Error()
	if strings.Contains(msg, "HTTP 404") && flags != nil && flags.ignoreMissing {
		return writeNoop(flags, "already_deleted", "already deleted (no-op)")
	}
	return classifyAPIError(err, flags)
}

func truncate(s string, max int) string {
	if len(s) <= max {
		return s
	}
	if max <= 3 {
		return s[:max]
	}
	return s[:max-3] + "..."
}

func replacePathParam(path, name, value string) string {
	return strings.ReplaceAll(path, "{"+name+"}", value)
}

// printJSONFiltered marshals a Go-typed value through the same output
// pipeline endpoint-mirror commands use. Hand-written novel commands that
// build a typed slice/struct call this so --select, --compact, --csv, and
// --quiet all behave the same way as on generator-emitted commands.
func printJSONFiltered(w io.Writer, v any, flags *rootFlags) error {
	raw, err := json.Marshal(v)
	if err != nil {
		return err
	}
	return printOutputWithFlags(w, json.RawMessage(raw), flags)
}

// printOutputWithFlags routes output through the right format based on flags.
//
// --select wins over --compact when both are set: an explicit field list is
// the user's authoritative request, so the high-gravity allow-list must not
// strip those fields out before --select can pick them. When only --compact
// is set (e.g., --agent without --select), the allow-list still runs.
func printOutputWithFlags(w io.Writer, data json.RawMessage, flags *rootFlags) error {
	switch {
	case flags.selectFields != "":
		data = filterFields(data, flags.selectFields)
	case flags.compact:
		data = compactFields(data)
	}
	if flags.quiet {
		return nil
	}
	if flags.csv {
		return printCSV(w, data)
	}
	return printOutput(w, data, flags.asJSON)
}

// printOutput auto-detects arrays and renders as tables, or prints raw JSON for objects.
func printOutput(w io.Writer, data json.RawMessage, asJSON bool) error {
	if !asJSON && !isTerminal(w) {
		asJSON = true
	}
	if asJSON {
		enc := json.NewEncoder(w)
		enc.SetIndent("", "  ")
		return enc.Encode(data)
	}

	var items []map[string]any
	if err := json.Unmarshal(data, &items); err == nil && len(items) > 0 {
		if err := printAutoTable(w, items); err != nil {
			return err
		}
		// Agent-friendly: show count and suggest narrowing when results are large.
		if len(items) >= 25 {
			fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
		}
		return nil
	}

	var obj map[string]any
	if err := json.Unmarshal(data, &obj); err == nil {
		enc := json.NewEncoder(w)
		enc.SetIndent("", "  ")
		return enc.Encode(obj)
	}

	fmt.Fprintln(w, string(data))
	return nil
}

// levenshteinDistance computes the edit distance between two strings using a two-row DP approach.
func levenshteinDistance(a, b string) int {
	if len(a) == 0 {
		return len(b)
	}
	if len(b) == 0 {
		return len(a)
	}
	if len(a) < len(b) {
		a, b = b, a
	}
	prev := make([]int, len(b)+1)
	curr := make([]int, len(b)+1)
	for j := range prev {
		prev[j] = j
	}
	for i := 1; i <= len(a); i++ {
		curr[0] = i
		for j := 1; j <= len(b); j++ {
			cost := 1
			if a[i-1] == b[j-1] {
				cost = 0
			}
			ins := curr[j-1] + 1
			del := prev[j] + 1
			sub := prev[j-1] + cost
			min := ins
			if del < min {
				min = del
			}
			if sub < min {
				min = sub
			}
			curr[j] = min
		}
		prev, curr = curr, prev
	}
	return prev[len(b)]
}

// suggestFlag returns the closest known flag name to the unknown string, or "" if none is close enough.
func suggestFlag(unknown string, cmd *cobra.Command) string {
	unknown = strings.TrimLeft(unknown, "-")
	best := ""
	bestDist := 4 // only consider distance <= 3
	check := func(name string) {
		d := levenshteinDistance(unknown, name)
		if d < bestDist && d*5 <= len(unknown)*2 {
			bestDist = d
			best = name
		}
	}
	cmd.Flags().VisitAll(func(f *pflag.Flag) { check(f.Name) })
	cmd.InheritedFlags().VisitAll(func(f *pflag.Flag) { check(f.Name) })
	return best
}

// DataProvenance describes where data came from and when it was last synced.
type DataProvenance struct {
	Source       string     `json:"source"`                  // "live" or "local"
	SyncedAt     *time.Time `json:"synced_at,omitempty"`     // when local data was last synced
	Reason       string     `json:"reason,omitempty"`        // why local was used: "user_requested", "api_unreachable", "no_search_endpoint"
	ResourceType string     `json:"resource_type,omitempty"` // which resource type was queried
	Freshness    any        `json:"freshness,omitempty"`     // optional machine-owned freshness metadata for covered command paths
}

// printProvenance writes a one-line provenance message to stderr for TTY users.
// Suppressed when stdout is piped or redirected — the JSON response envelope
// already carries meta.source, so the stderr line is redundant and becomes
// noise in agent flows that merge stderr into stdout.
func printProvenance(cmd *cobra.Command, count int, prov DataProvenance) {
	if !isTerminal(cmd.OutOrStdout()) {
		return
	}
	if prov.Source == "live" {
		fmt.Fprintf(cmd.ErrOrStderr(), "%d results (live)\n", count)
		return
	}
	prefix := ""
	if prov.Reason == "api_unreachable" {
		prefix = "API unreachable. "
	}
	fmt.Fprintf(cmd.ErrOrStderr(), "%s%d results (cached, synced %s)\n", prefix, count, formatProvenanceAge(prov.SyncedAt))
}

func formatProvenanceAge(syncedAt *time.Time) string {
	if syncedAt == nil {
		return "unknown"
	}
	d := time.Since(*syncedAt)
	switch {
	case d < time.Minute:
		return "just now"
	case d < time.Hour:
		return fmt.Sprintf("%d minutes ago", int(d.Minutes()))
	case d < 24*time.Hour:
		return fmt.Sprintf("%d hours ago", int(d.Hours()))
	default:
		return fmt.Sprintf("%d days ago", int(d.Hours()/24))
	}
}

// wrapWithProvenance wraps response data in a provenance envelope:
// {"results": ..., "meta": {...}}. When data is valid JSON, it embeds as
// the parsed shape; when data is non-JSON (e.g., XML/RSS responses, plain
// text), it embeds as a JSON string so json.Marshal doesn't choke on
// "invalid character '<'" while still passing the raw payload through to
// the consumer.
func wrapWithProvenance(data json.RawMessage, prov DataProvenance) (json.RawMessage, error) {
	meta := map[string]any{"source": prov.Source}
	if prov.SyncedAt != nil {
		meta["synced_at"] = prov.SyncedAt.UTC().Format(time.RFC3339)
	}
	if prov.Reason != "" {
		meta["reason"] = prov.Reason
	}
	if prov.ResourceType != "" {
		meta["resource_type"] = prov.ResourceType
	}
	if prov.Freshness != nil {
		meta["freshness"] = prov.Freshness
	}
	var results any = json.RawMessage(data)
	if !json.Valid(data) {
		results = string(data)
	}
	envelope := map[string]any{
		"results": results,
		"meta":    meta,
	}
	return json.Marshal(envelope)
}

// defaultDBPath returns the canonical path for the local SQLite database.
func defaultDBPath(name string) string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".local", "share", name, "data.db")
}
