// Copyright 2026 olga-safonova. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newOauthCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "oauth",
		Short: "Manage oauth",
	}

	cmd.AddCommand(newOauthRevokeTokenCmd(flags))
	cmd.AddCommand(newOauthRevokeTokenV2Cmd(flags))
	return cmd
}
