// Copyright 2026 olga-safonova. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newOauthRevokeTokenV2Cmd(flags *rootFlags) *cobra.Command {
	var bodyAccessToken string
	var bodyClientId string
	var bodyClientSecret string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "revoke-token-v2",
		Short:       "Revoke the current access token. Revoking an access token means that the access token will no longer work. When an...",
		Example:     "  miro-cli oauth revoke-token-v2 --access-token your-token-here",
		Annotations: map[string]string{"pp:endpoint": "oauth.revoke-token-v2", "pp:method": "POST", "pp:path": "/v2/oauth/revoke"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !stdinBody {
				if !cmd.Flags().Changed("access-token") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "access-token")
				}
				if !cmd.Flags().Changed("client-id") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "client-id")
				}
				if !cmd.Flags().Changed("client-secret") && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "client-secret")
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/v2/oauth/revoke"
			var body any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				if err := json.Unmarshal(stdinData, &body); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
			} else {
				bodyFields := map[string]any{}
				if bodyAccessToken != "" {
					bodyFields["accessToken"] = bodyAccessToken
				}
				if bodyClientId != "" {
					bodyFields["clientId"] = bodyClientId
				}
				if bodyClientSecret != "" {
					bodyFields["clientSecret"] = bodyClientSecret
				}
				body = bodyFields
			}
			data, statusCode, err := c.Post(path, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							return nil
						}
					}
				}
			}
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				if flags.quiet {
					return nil
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "oauth",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300,
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				return printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true)
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&bodyAccessToken, "access-token", "", "The access token to be revoked.")
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "The client ID associated with the access token.")
	cmd.Flags().StringVar(&bodyClientSecret, "client-secret", "", "The client secret associated with the access token.")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
