// Copyright 2026 olga-safonova. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newOrgsTeamsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "teams",
		Short: "Manage teams",
	}

	cmd.AddCommand(newOrgsTeamsEnterpriseAddProjectMemberCmd(flags))
	cmd.AddCommand(newOrgsTeamsEnterpriseCreateCmd(flags))
	cmd.AddCommand(newOrgsTeamsEnterpriseCreateGroupCmd(flags))
	cmd.AddCommand(newOrgsTeamsEnterpriseCreateProjectCmd(flags))
	cmd.AddCommand(newOrgsTeamsEnterpriseDataclassificationBoardGetCmd(flags))
	cmd.AddCommand(newOrgsTeamsEnterpriseDataclassificationBoardSetCmd(flags))
	cmd.AddCommand(newOrgsTeamsEnterpriseDataclassificationBoardsBulkCmd(flags))
	cmd.AddCommand(newOrgsTeamsEnterpriseDataclassificationSettingsGetCmd(flags))
	cmd.AddCommand(newOrgsTeamsEnterpriseDataclassificationSettingsSetCmd(flags))
	cmd.AddCommand(newOrgsTeamsEnterpriseDeleteCmd(flags))
	cmd.AddCommand(newOrgsTeamsEnterpriseDeleteGroupCmd(flags))
	cmd.AddCommand(newOrgsTeamsEnterpriseDeleteMemberCmd(flags))
	cmd.AddCommand(newOrgsTeamsEnterpriseDeleteProjectCmd(flags))
	cmd.AddCommand(newOrgsTeamsEnterpriseDeleteProjectMemberCmd(flags))
	cmd.AddCommand(newOrgsTeamsEnterpriseGetCmd(flags))
	cmd.AddCommand(newOrgsTeamsEnterpriseGetGroupCmd(flags))
	cmd.AddCommand(newOrgsTeamsEnterpriseGetGroupsCmd(flags))
	cmd.AddCommand(newOrgsTeamsEnterpriseGetMemberCmd(flags))
	cmd.AddCommand(newOrgsTeamsEnterpriseGetMembersCmd(flags))
	cmd.AddCommand(newOrgsTeamsEnterpriseGetOrgsCmd(flags))
	cmd.AddCommand(newOrgsTeamsEnterpriseGetProjectCmd(flags))
	cmd.AddCommand(newOrgsTeamsEnterpriseGetProjectMemberCmd(flags))
	cmd.AddCommand(newOrgsTeamsEnterpriseGetProjectMembersCmd(flags))
	cmd.AddCommand(newOrgsTeamsEnterpriseGetProjectSettingsCmd(flags))
	cmd.AddCommand(newOrgsTeamsEnterpriseGetProjectsCmd(flags))
	cmd.AddCommand(newOrgsTeamsEnterpriseGetSettingsCmd(flags))
	cmd.AddCommand(newOrgsTeamsEnterpriseInviteMemberCmd(flags))
	cmd.AddCommand(newOrgsTeamsEnterpriseUpdateCmd(flags))
	cmd.AddCommand(newOrgsTeamsEnterpriseUpdateMemberCmd(flags))
	cmd.AddCommand(newOrgsTeamsEnterpriseUpdateProjectCmd(flags))
	cmd.AddCommand(newOrgsTeamsEnterpriseUpdateProjectMemberCmd(flags))
	cmd.AddCommand(newOrgsTeamsEnterpriseUpdateProjectSettingsCmd(flags))
	cmd.AddCommand(newOrgsTeamsEnterpriseUpdateSettingsCmd(flags))
	return cmd
}
