// Copyright 2026 olga-safonova. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newOrgsTeamsEnterpriseGetProjectMembersCmd(flags *rootFlags) *cobra.Command {
	var flagLimit int
	var flagCursor string
	var flagAll bool

	cmd := &cobra.Command{
		Use:   "enterprise-get-project-members <org_id> <team_id> <project_id>",
		Short: "Retrieves the list of members for a specific project.<h4>Note</h4> <em>Projects</em> have been renamed...",
		Example: "  miro-developer-platform-pp-cli orgs teams enterprise-get-project-members 550e8400-e29b-41d4-a716-446655440000 550e8400-e29b-41d4-a716-446655440000 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "teams.enterprise-get-project-members", "pp:method": "GET", "pp:path": "/v2/orgs/{org_id}/teams/{team_id}/projects/{project_id}/members", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/v2/orgs/{org_id}/teams/{team_id}/projects/{project_id}/members"
			path = replacePathParam(path, "org_id", args[0])
			if len(args) < 2 {
				return usageErr(fmt.Errorf("team_id is required\nUsage: %s <%s>", cmd.CommandPath(), "team_id"))
			}
			path = replacePathParam(path, "team_id", args[1])
			if len(args) < 3 {
				return usageErr(fmt.Errorf("project_id is required\nUsage: %s <%s>", cmd.CommandPath(), "project_id"))
			}
			path = replacePathParam(path, "project_id", args[2])
			data, prov, err := resolvePaginatedRead(cmd.Context(), c, flags, "teams", path, map[string]string{
				"limit": fmt.Sprintf("%v", flagLimit),
				"cursor": fmt.Sprintf("%v", flagCursor),
			}, nil, flagAll, "cursor", "", "")
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Unwrap single-key array-wrapper responses (e.g. {"tags":[...]},
			// {"items":[...]}) so the count, table, and provenance envelope all
			// see the inner list. Multi-key wrappers (paginated lists with
			// cursor/total fields) pass through unchanged.
			data = unwrapListResponse(data)
			// Print provenance to stderr for human-facing output
			{
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested.
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().IntVar(&flagLimit, "limit", 100, "The maximum number of results to return per call. If the number of project members in the response is greater than...")
	cmd.Flags().StringVar(&flagCursor, "cursor", "", "An indicator of the position of a page in the full set of results. To obtain the first page leave it empty. To...")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	return cmd
}
