// Copyright 2026 olga-safonova. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newOrgsProjectsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "projects",
		Short: "Manage projects",
	}

	cmd.AddCommand(newOrgsProjectsEnterpriseCreateGroupCmd(flags))
	cmd.AddCommand(newOrgsProjectsEnterpriseDeleteGroupsCmd(flags))
	cmd.AddCommand(newOrgsProjectsEnterpriseGetGroupsCmd(flags))
	return cmd
}
