// Copyright 2026 olga-safonova. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newOrgsBoardsEnterpriseCreateExportCmd(flags *rootFlags) *cobra.Command {
	var flagRequestId string
	var bodyBoardFormat string
	var bodyBoardIds string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:   "enterprise-create-export <org_id>",
		Aliases: []string{"create"},
		Short: "Creates an export job for one or more boards.<br/><h3>Required scope</h3> <a target=_blank...",
		Example: "  miro-developer-platform-pp-cli orgs boards enterprise-create-export 550e8400-e29b-41d4-a716-446655440000 --request-id 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "boards.enterprise-create-export", "pp:method": "POST", "pp:path": "/v2/orgs/{org_id}/boards/export/jobs"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			if !cmd.Flags().Changed("request-id") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "request-id")
			}
			if !stdinBody {
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/v2/orgs/{org_id}/boards/export/jobs"
			path = replacePathParam(path, "org_id", args[0])
			queryParams := map[string]string{}
			if flagRequestId != "" {
				queryParams["request_id"] = fmt.Sprintf("%v", flagRequestId)
			}
			var body any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				if err := json.Unmarshal(stdinData, &body); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
			} else {
				bodyFields := map[string]any{}
				if bodyBoardFormat != "" {
					bodyFields["boardFormat"] = bodyBoardFormat
				}
				if bodyBoardIds != "" {
					var parsedBoardIds any
					if err := json.Unmarshal([]byte(bodyBoardIds), &parsedBoardIds); err != nil {
						return fmt.Errorf("parsing --board-ids JSON: %w", err)
					}
					bodyFields["boardIds"] = parsedBoardIds
				}
				body = bodyFields
			}
			data, statusCode, err := c.PostWithParams(path, queryParams, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						return nil
					}
				} else {
					var wrapped struct{ Data []map[string]any `json:"data"` }
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							return nil
						}
					}
				}
			}
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				if flags.quiet {
					return nil
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "boards",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300,
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				return printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true)
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagRequestId, "request-id", "", "Unique identifier of the board export job.")
	cmd.Flags().StringVar(&bodyBoardFormat, "board-format", "SVG", "Specifies the format of the file to which the board will be exported. Supported formats include SVG (default), HTML,...")
	cmd.Flags().StringVar(&bodyBoardIds, "board-ids", "", "List of board IDs to be exported. Each export job can contain up to 1,000 boards.")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
