// Copyright 2026 olga-safonova. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newOrgsAiInteractionLogsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "ai-interaction-logs",
		Short: "Manage ai interaction logs",
	}

	cmd.AddCommand(newOrgsAiInteractionLogsEnterpriseGetCmd(flags))
	return cmd
}
