// Copyright 2026 olga-safonova. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newOrgsMembersEnterpriseGetOrganizationCmd(flags *rootFlags) *cobra.Command {
	var flagEmails string
	var flagRole string
	var flagLicense string
	var flagActive bool
	var flagCursor string
	var flagLimit int
	var flagAll bool

	cmd := &cobra.Command{
		Use:         "enterprise-get-organization <org_id>",
		Aliases:     []string{"get"},
		Short:       "Retrieves organization members based on the organization ID and the cursor, or based on the user emails provided in...",
		Example:     "  miro-developer-platform-pp-cli orgs members enterprise-get-organization 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "members.enterprise-get-organization", "pp:method": "GET", "pp:path": "/v2/orgs/{org_id}/members", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			if cmd.Flags().Changed("role") {
				allowedRole := []string{"organization_internal_admin", "organization_internal_user", "organization_external_user", "organization_team_guest_user", "unknown"}
				validRole := false
				for _, v := range allowedRole {
					if flagRole == v {
						validRole = true
						break
					}
				}
				if !validRole {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "role", flagRole, allowedRole)
				}
			}
			if cmd.Flags().Changed("license") {
				allowedLicense := []string{"advanced", "standard", "basic", "full", "occasional", "free", "free_restricted", "full_trial", "unknown"}
				validLicense := false
				for _, v := range allowedLicense {
					if flagLicense == v {
						validLicense = true
						break
					}
				}
				if !validLicense {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "license", flagLicense, allowedLicense)
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/v2/orgs/{org_id}/members"
			path = replacePathParam(path, "org_id", args[0])
			data, prov, err := resolvePaginatedRead(cmd.Context(), c, flags, "members", path, map[string]string{
				"emails":  fmt.Sprintf("%v", flagEmails),
				"role":    fmt.Sprintf("%v", flagRole),
				"license": fmt.Sprintf("%v", flagLicense),
				"active":  fmt.Sprintf("%v", flagActive),
				"cursor":  fmt.Sprintf("%v", flagCursor),
				"limit":   fmt.Sprintf("%v", flagLimit),
			}, nil, flagAll, "cursor", "", "")
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Unwrap single-key array-wrapper responses (e.g. {"tags":[...]},
			// {"items":[...]}) so the count, table, and provenance envelope all
			// see the inner list. Multi-key wrappers (paginated lists with
			// cursor/total fields) pass through unchanged.
			data = unwrapListResponse(data)
			// Print provenance to stderr for human-facing output
			{
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested.
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagEmails, "emails", "", "Emails")
	cmd.Flags().StringVar(&flagRole, "role", "", "Role (one of: organization_internal_admin, organization_internal_user, organization_external_user, organization_team_guest_user, unknown)")
	cmd.Flags().StringVar(&flagLicense, "license", "", "License (one of: advanced, standard, basic, full, occasional, free, free_restricted, full_trial, unknown)")
	cmd.Flags().BoolVar(&flagActive, "active", false, "Active")
	cmd.Flags().StringVar(&flagCursor, "cursor", "", "Cursor")
	cmd.Flags().IntVar(&flagLimit, "limit", 100, "Limit")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	return cmd
}
