// Copyright 2026 olga-safonova. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newOrgsCasesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "cases",
		Short: "Manage cases",
	}

	cmd.AddCommand(newOrgsCasesCreateCmd(flags))
	cmd.AddCommand(newOrgsCasesCreateLegalHoldCmd(flags))
	cmd.AddCommand(newOrgsCasesDeleteCmd(flags))
	cmd.AddCommand(newOrgsCasesDeleteLegalHoldCmd(flags))
	cmd.AddCommand(newOrgsCasesEditCmd(flags))
	cmd.AddCommand(newOrgsCasesEditLegalHoldCmd(flags))
	cmd.AddCommand(newOrgsCasesGetCmd(flags))
	cmd.AddCommand(newOrgsCasesGetAllCmd(flags))
	cmd.AddCommand(newOrgsCasesGetAllLegalHoldsCmd(flags))
	cmd.AddCommand(newOrgsCasesGetLegalHoldCmd(flags))
	cmd.AddCommand(newOrgsCasesGetLegalHoldContentItemsCmd(flags))
	cmd.AddCommand(newOrgsCasesGetLegalHoldExportJobsCmd(flags))
	return cmd
}
