// Copyright 2026 olga-safonova. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newOrgsBoardsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "boards",
		Short: "Manage boards",
	}

	cmd.AddCommand(newOrgsBoardsEnterpriseCreateExportCmd(flags))
	cmd.AddCommand(newOrgsBoardsEnterpriseCreateExportTaskExportLinkCmd(flags))
	cmd.AddCommand(newOrgsBoardsEnterpriseCreateGroupCmd(flags))
	cmd.AddCommand(newOrgsBoardsEnterpriseDeleteGroupsCmd(flags))
	cmd.AddCommand(newOrgsBoardsEnterpriseExportJobResultsCmd(flags))
	cmd.AddCommand(newOrgsBoardsEnterpriseExportJobStatusCmd(flags))
	cmd.AddCommand(newOrgsBoardsEnterpriseExportJobTasksCmd(flags))
	cmd.AddCommand(newOrgsBoardsEnterpriseExportJobsCmd(flags))
	cmd.AddCommand(newOrgsBoardsEnterpriseGetGroupsCmd(flags))
	cmd.AddCommand(newOrgsBoardsEnterpriseUpdateExportJobCmd(flags))
	return cmd
}
