// Copyright 2026 olga-safonova. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newOrgsBoardsEnterpriseExportJobTasksCmd(flags *rootFlags) *cobra.Command {
	var flagStatus string
	var flagCursor string
	var flagLimit int
	var flagAll bool

	cmd := &cobra.Command{
		Use:   "enterprise-export-job-tasks <org_id> <job_id>",
		Short: "Retrieves the list of tasks for the board export job.<br/><h3>Required scope</h3> <a target=_blank...",
		Example: "  miro-developer-platform-pp-cli orgs boards enterprise-export-job-tasks 550e8400-e29b-41d4-a716-446655440000 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "boards.enterprise-export-job-tasks", "pp:method": "GET", "pp:path": "/v2/orgs/{org_id}/boards/export/jobs/{job_id}/tasks", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/v2/orgs/{org_id}/boards/export/jobs/{job_id}/tasks"
			path = replacePathParam(path, "org_id", args[0])
			if len(args) < 2 {
				return usageErr(fmt.Errorf("job_id is required\nUsage: %s <%s>", cmd.CommandPath(), "job_id"))
			}
			path = replacePathParam(path, "job_id", args[1])
			data, prov, err := resolvePaginatedRead(cmd.Context(), c, flags, "boards", path, map[string]string{
				"status": fmt.Sprintf("%v", flagStatus),
				"cursor": fmt.Sprintf("%v", flagCursor),
				"limit": fmt.Sprintf("%v", flagLimit),
			}, nil, flagAll, "cursor", "", "")
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Unwrap single-key array-wrapper responses (e.g. {"tags":[...]},
			// {"items":[...]}) so the count, table, and provenance envelope all
			// see the inner list. Multi-key wrappers (paginated lists with
			// cursor/total fields) pass through unchanged.
			data = unwrapListResponse(data)
			// Print provenance to stderr for human-facing output
			{
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested.
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagStatus, "status", "", "Filters the list of board export tasks by their status. Accepts an array of statuses such as TASK_STATUS_CREATED,...")
	cmd.Flags().StringVar(&flagCursor, "cursor", "", "A cursor-paginated method returns a portion of the total set of results based on the limit specified and a cursor...")
	cmd.Flags().IntVar(&flagLimit, "limit", 50, "The maximum number of results to return per call. If the number of tasks in the response is greater than the limit...")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	return cmd
}
