// Copyright 2026 olga-safonova. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newOrgsGroupsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "groups",
		Short: "Manage groups",
	}

	cmd.AddCommand(newOrgsGroupsEnterpriseCreateCmd(flags))
	cmd.AddCommand(newOrgsGroupsEnterpriseCreateMemberCmd(flags))
	cmd.AddCommand(newOrgsGroupsEnterpriseDeleteCmd(flags))
	cmd.AddCommand(newOrgsGroupsEnterpriseDeleteMemberCmd(flags))
	cmd.AddCommand(newOrgsGroupsEnterpriseGetCmd(flags))
	cmd.AddCommand(newOrgsGroupsEnterpriseGetMemberCmd(flags))
	cmd.AddCommand(newOrgsGroupsEnterpriseGetMembersCmd(flags))
	cmd.AddCommand(newOrgsGroupsEnterpriseGetOrgsCmd(flags))
	cmd.AddCommand(newOrgsGroupsEnterpriseGetTeamCmd(flags))
	cmd.AddCommand(newOrgsGroupsEnterpriseGetTeamsCmd(flags))
	cmd.AddCommand(newOrgsGroupsEnterpriseUpdateCmd(flags))
	cmd.AddCommand(newOrgsGroupsEnterpriseUpdateMembersCmd(flags))
	return cmd
}
