// Copyright 2026 olga-safonova. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newOrgsContentLogsEnterpriseBoardContentItemLogsFetchCmd(flags *rootFlags) *cobra.Command {
	var flagBoardIds string
	var flagEmails string
	var flagFrom string
	var flagTo string
	var flagCursor string
	var flagLimit int
	var flagSorting string
	var flagAll bool

	cmd := &cobra.Command{
		Use:         "enterprise-board-content-item-logs-fetch <org_id>",
		Aliases:     []string{"get"},
		Short:       "Retrieves content changes for board items within your organization. Content changes are actions that users can...",
		Example:     "  miro-cli orgs content-logs enterprise-board-content-item-logs-fetch 550e8400-e29b-41d4-a716-446655440000 --from 2026-01-15T09:00:00Z --to 2026-01-15T09:00:00Z",
		Annotations: map[string]string{"pp:endpoint": "content-logs.enterprise-board-content-item-logs-fetch", "pp:method": "GET", "pp:path": "/v2/orgs/{org_id}/content-logs/items", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			if !cmd.Flags().Changed("from") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "from")
			}
			if !cmd.Flags().Changed("to") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "to")
			}
			if cmd.Flags().Changed("sorting") {
				allowedSorting := []string{"asc", "desc"}
				validSorting := false
				for _, v := range allowedSorting {
					if flagSorting == v {
						validSorting = true
						break
					}
				}
				if !validSorting {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "sorting", flagSorting, allowedSorting)
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/v2/orgs/{org_id}/content-logs/items"
			path = replacePathParam(path, "org_id", args[0])
			data, prov, err := resolvePaginatedRead(cmd.Context(), c, flags, "content-logs", path, map[string]string{
				"board_ids": fmt.Sprintf("%v", flagBoardIds),
				"emails":    fmt.Sprintf("%v", flagEmails),
				"from":      fmt.Sprintf("%v", flagFrom),
				"to":        fmt.Sprintf("%v", flagTo),
				"cursor":    fmt.Sprintf("%v", flagCursor),
				"limit":     fmt.Sprintf("%v", flagLimit),
				"sorting":   fmt.Sprintf("%v", flagSorting),
			}, nil, flagAll, "cursor", "", "")
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Unwrap single-key array-wrapper responses (e.g. {"tags":[...]},
			// {"items":[...]}) so the count, table, and provenance envelope all
			// see the inner list. Multi-key wrappers (paginated lists with
			// cursor/total fields) pass through unchanged.
			data = unwrapListResponse(data)
			// Print provenance to stderr for human-facing output
			{
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested.
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagBoardIds, "board-ids", "", "List of board IDs for which you want to retrieve the content logs.")
	cmd.Flags().StringVar(&flagEmails, "emails", "", "Filter content logs based on the list of emails of users who created, modified, or deleted the board item.")
	cmd.Flags().StringVar(&flagFrom, "from", "", "Filter content logs based on the date and time when the board item was last modified. This is the start date and...")
	cmd.Flags().StringVar(&flagTo, "to", "", "Filter content logs based on the date and time when the board item was last modified. This is the end date and time...")
	cmd.Flags().StringVar(&flagCursor, "cursor", "", "A cursor-paginated method returns a portion of the total set of results based on the limit specified and a cursor...")
	cmd.Flags().IntVar(&flagLimit, "limit", 1000, "The maximum number of results to return per call. If the number of logs in the response is greater than the limit...")
	cmd.Flags().StringVar(&flagSorting, "sorting", "asc", "Sort order in which you want to view the result set based on the modified date. To sort by an ascending modified... (one of: asc, desc)")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	return cmd
}
