// Copyright 2026 olga-safonova. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newOrgsTeamsEnterpriseUpdateSettingsCmd(flags *rootFlags) *cobra.Command {
	var bodyTeamAccountDiscoverySettings string
	var bodyTeamCollaborationSettings string
	var bodyTeamCopyAccessLevelSettings string
	var bodyTeamInvitationSettings string
	var bodyTeamSharingPolicySettings string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "enterprise-update-settings <org_id> <team_id>",
		Short:       "Updates team settings of an existing team.<br/><h3>Required scope</h3> <a target=_blank...",
		Example:     "  miro-cli orgs teams enterprise-update-settings 550e8400-e29b-41d4-a716-446655440000 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "teams.enterprise-update-settings", "pp:method": "PATCH", "pp:path": "/v2/orgs/{org_id}/teams/{team_id}/settings"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			if !stdinBody {
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/v2/orgs/{org_id}/teams/{team_id}/settings"
			path = replacePathParam(path, "org_id", args[0])
			if len(args) < 2 {
				return usageErr(fmt.Errorf("team_id is required\nUsage: %s <%s>", cmd.CommandPath(), "team_id"))
			}
			path = replacePathParam(path, "team_id", args[1])
			var body any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				if err := json.Unmarshal(stdinData, &body); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
			} else {
				bodyFields := map[string]any{}
				if bodyTeamAccountDiscoverySettings != "" {
					var parsedTeamAccountDiscoverySettings any
					if err := json.Unmarshal([]byte(bodyTeamAccountDiscoverySettings), &parsedTeamAccountDiscoverySettings); err != nil {
						return fmt.Errorf("parsing --team-account-discovery-settings JSON: %w", err)
					}
					bodyFields["teamAccountDiscoverySettings"] = parsedTeamAccountDiscoverySettings
				}
				if bodyTeamCollaborationSettings != "" {
					var parsedTeamCollaborationSettings any
					if err := json.Unmarshal([]byte(bodyTeamCollaborationSettings), &parsedTeamCollaborationSettings); err != nil {
						return fmt.Errorf("parsing --team-collaboration-settings JSON: %w", err)
					}
					bodyFields["teamCollaborationSettings"] = parsedTeamCollaborationSettings
				}
				if bodyTeamCopyAccessLevelSettings != "" {
					var parsedTeamCopyAccessLevelSettings any
					if err := json.Unmarshal([]byte(bodyTeamCopyAccessLevelSettings), &parsedTeamCopyAccessLevelSettings); err != nil {
						return fmt.Errorf("parsing --team-copy-access-level-settings JSON: %w", err)
					}
					bodyFields["teamCopyAccessLevelSettings"] = parsedTeamCopyAccessLevelSettings
				}
				if bodyTeamInvitationSettings != "" {
					var parsedTeamInvitationSettings any
					if err := json.Unmarshal([]byte(bodyTeamInvitationSettings), &parsedTeamInvitationSettings); err != nil {
						return fmt.Errorf("parsing --team-invitation-settings JSON: %w", err)
					}
					bodyFields["teamInvitationSettings"] = parsedTeamInvitationSettings
				}
				if bodyTeamSharingPolicySettings != "" {
					var parsedTeamSharingPolicySettings any
					if err := json.Unmarshal([]byte(bodyTeamSharingPolicySettings), &parsedTeamSharingPolicySettings); err != nil {
						return fmt.Errorf("parsing --team-sharing-policy-settings JSON: %w", err)
					}
					bodyFields["teamSharingPolicySettings"] = parsedTeamSharingPolicySettings
				}
				body = bodyFields
			}
			data, statusCode, err := c.Patch(path, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							return nil
						}
					}
				}
			}
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				if flags.quiet {
					return nil
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				envelope := map[string]any{
					"action":   "patch",
					"resource": "teams",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300,
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				return printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true)
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&bodyTeamAccountDiscoverySettings, "team-account-discovery-settings", "", "Team account discovery settings")
	cmd.Flags().StringVar(&bodyTeamCollaborationSettings, "team-collaboration-settings", "", "Team collaboration settings")
	cmd.Flags().StringVar(&bodyTeamCopyAccessLevelSettings, "team-copy-access-level-settings", "", "Team copy access settings")
	cmd.Flags().StringVar(&bodyTeamInvitationSettings, "team-invitation-settings", "", "Team invitation settings")
	cmd.Flags().StringVar(&bodyTeamSharingPolicySettings, "team-sharing-policy-settings", "", "Team sharing policy settings")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
