// Copyright 2026 olga-safonova. Licensed under Apache-2.0. See LICENSE.
//
// Hand-authored — extracted from helpers.go during the cohesion-split
// refactor. Do not re-add the "Generated by CLI Printing Press" marker;
// the regenmerge pass uses that marker to decide what to clobber.
//
// Responsibility: drive paginated GETs across the generated client. The
// public paginatedGet signature is preserved (8 args) because it is called
// from many generator-emitted endpoint files; changing the signature here
// would force every caller into hand-authored opt-out. The body is
// internally split into smaller helpers to address the "Brain Method" /
// "Bumpy Road" / "Deep Nesting" smells the original carried.

package cli

import (
	"encoding/json"
	"fmt"
	"os"
)

// pageFetchClient is the minimal client surface the pagination loop needs.
// Defined here so paginatedGet does not depend on the full *client.Client
// type (keeps the package boundary clean and the function trivially mockable
// in tests).
type pageFetchClient interface {
	GetWithHeaders(path string, params map[string]string, headers map[string]string) (json.RawMessage, error)
}

// paginatedGet fetches pages and concatenates array results. The headers
// argument carries per-endpoint required headers (e.g. cal-api-version) that
// must be sent on every page request, including the first; pass nil when the
// endpoint has no per-endpoint header overrides.
func paginatedGet(c pageFetchClient, path string, params map[string]string, headers map[string]string, fetchAll bool, cursorParam, nextCursorPath, hasMoreField string) (json.RawMessage, error) {
	clean := cleanPaginationParams(params)
	if !fetchAll {
		return c.GetWithHeaders(path, clean, headers)
	}

	allItems := make([]json.RawMessage, 0)
	page := 0
	for {
		page++
		emitPageEvent(page)

		data, err := c.GetWithHeaders(path, clean, headers)
		if err != nil {
			return nil, err
		}

		items, hasMore := readNextPage(data, clean, cursorParam, nextCursorPath, hasMoreField)
		allItems = append(allItems, items...)
		if !hasMore {
			break
		}
	}

	emitCompleteEvent(len(allItems), page)
	result, _ := json.Marshal(allItems)
	return json.RawMessage(result), nil
}

// cleanPaginationParams strips zero-value entries so the wire request stays
// tidy and downstream cache keys do not include placeholder values.
func cleanPaginationParams(params map[string]string) map[string]string {
	clean := map[string]string{}
	for k, v := range params {
		if v != "" && v != "0" && v != "false" {
			clean[k] = v
		}
	}
	return clean
}

func emitPageEvent(page int) {
	if humanFriendly {
		fmt.Fprintf(os.Stderr, "fetching page %d...\n", page)
		return
	}
	fmt.Fprintf(os.Stderr, `{"event":"page_fetch","page":%d}`+"\n", page)
}

func emitCompleteEvent(total, pages int) {
	if humanFriendly {
		fmt.Fprintf(os.Stderr, "fetched %d items across %d pages\n", total, pages)
		return
	}
	fmt.Fprintf(os.Stderr, `{"event":"complete","total":%d,"pages":%d}`+"\n", total, pages)
}

// readNextPage parses one fetch response into items and updates the
// pagination cursor in `clean` for the next iteration. Returns hasMore=false
// when the response is a direct array (cannot paginate without a cursor) or
// when neither the cursor nor the has-more field signal continuation.
func readNextPage(data json.RawMessage, clean map[string]string, cursorParam, nextCursorPath, hasMoreField string) ([]json.RawMessage, bool) {
	// Direct array response: append and stop (no cursor available).
	var direct []json.RawMessage
	if json.Unmarshal(data, &direct) == nil {
		return direct, false
	}

	// Object response: look for an array inside, then check pagination signals.
	var obj map[string]json.RawMessage
	if json.Unmarshal(data, &obj) != nil {
		return nil, false
	}
	items, _ := extractPaginatedItems(obj)

	if advanceCursor(obj, clean, cursorParam, nextCursorPath) {
		return items, true
	}
	if hasMore(obj, hasMoreField) {
		return items, true
	}
	return items, false
}

// advanceCursor reads the next-cursor token (if any) and writes it into
// clean[cursorParam]. Returns true when a non-empty cursor was found and
// written (meaning the loop should continue).
func advanceCursor(obj map[string]json.RawMessage, clean map[string]string, cursorParam, nextCursorPath string) bool {
	if nextCursorPath == "" {
		return false
	}
	tokenRaw, ok := rawAtPath(obj, nextCursorPath)
	if !ok {
		return false
	}
	var token string
	if err := json.Unmarshal(tokenRaw, &token); err != nil || token == "" {
		return false
	}
	clean[cursorParam] = token
	return true
}

// hasMore reads the boolean has-more field (if any) and returns its value.
func hasMore(obj map[string]json.RawMessage, hasMoreField string) bool {
	if hasMoreField == "" {
		return false
	}
	moreRaw, ok := rawAtPath(obj, hasMoreField)
	if !ok {
		return false
	}
	var more bool
	if err := json.Unmarshal(moreRaw, &more); err != nil {
		return false
	}
	return more
}

// extractPaginatedItems pulls the items array out of a paginated response
// object. Tries known wrapper keys (data, items, results, ...) first; falls
// back to "the only array-typed property" when exactly one such property
// exists.
func extractPaginatedItems(obj map[string]json.RawMessage) ([]json.RawMessage, bool) {
	for _, field := range []string{"data", "items", "results", "messages", "members", "values"} {
		arr, ok := obj[field]
		if !ok {
			continue
		}
		var nested []json.RawMessage
		if json.Unmarshal(arr, &nested) == nil {
			return nested, true
		}
	}

	var onlyArray []json.RawMessage
	arrayCount := 0
	for _, raw := range obj {
		var candidate []json.RawMessage
		if json.Unmarshal(raw, &candidate) == nil {
			onlyArray = candidate
			arrayCount++
		}
	}
	if arrayCount == 1 {
		return onlyArray, true
	}
	return nil, false
}
