// Copyright 2026 olga-safonova. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newAuditPromotedCmd(flags *rootFlags) *cobra.Command {
	var flagCreatedAfter string
	var flagCreatedBefore string
	var flagCursor string
	var flagLimit int
	var flagSorting string
	var flagAll bool

	cmd := &cobra.Command{
		Use:         "audit",
		Short:       "Retrieves a page of audit events from the last 90 days. If you want to retrieve data that is older than 90 days, you...",
		Long:        "Shortcut for 'audit enterprise-get-logs'. Retrieves a page of audit events from the last 90 days. If you want to retrieve data that is older than 90 days, you...",
		Example:     "  miro-cli audit --created-after example-value --created-before example-value",
		Annotations: map[string]string{"pp:endpoint": "audit.enterprise-get-logs", "pp:method": "GET", "pp:path": "/v2/audit/logs", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !cmd.Flags().Changed("created-after") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "created-after")
			}
			if !cmd.Flags().Changed("created-before") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "created-before")
			}
			if cmd.Flags().Changed("sorting") {
				allowedSorting := []string{"ASC", "DESC"}
				validSorting := false
				for _, v := range allowedSorting {
					if flagSorting == v {
						validSorting = true
						break
					}
				}
				if !validSorting {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "sorting", flagSorting, allowedSorting)
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/v2/audit/logs"
			data, prov, err := resolvePaginatedRead(cmd.Context(), c, flags, "audit", path, map[string]string{
				"createdAfter":  fmt.Sprintf("%v", flagCreatedAfter),
				"createdBefore": fmt.Sprintf("%v", flagCreatedBefore),
				"cursor":        fmt.Sprintf("%v", flagCursor),
				"limit":         fmt.Sprintf("%v", flagLimit),
				"sorting":       fmt.Sprintf("%v", flagSorting),
			}, nil, flagAll, "cursor", "", "")
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Unwrap API response envelopes (e.g. {"status":"success","data":[...]})
			// so output helpers see the inner data, not the wrapper.
			data = extractResponseData(data)

			// Print provenance to stderr
			{
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// CSV bypasses JSON pipe path so --csv works when piped
			if flags.csv {
				return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested.
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagCreatedAfter, "created-after", "", "Retrieve audit logs created after the date and time provided. This is the start date of the duration for which you...")
	cmd.Flags().StringVar(&flagCreatedBefore, "created-before", "", "Retrieve audit logs created before the date and time provided. This is the end date of the duration for which you...")
	cmd.Flags().StringVar(&flagCursor, "cursor", "", "A cursor-paginated method returns a portion of the total set of results based on the `limit` specified and a...")
	cmd.Flags().IntVar(&flagLimit, "limit", 0, "Maximum number of results returned based on the `limit` specified in the request. For example, if there are `30`...")
	cmd.Flags().StringVar(&flagSorting, "sorting", "", "Sort order in which you want to view the result set. Based on the value you provide, the results are sorted in an... (one of: ASC, DESC)")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
