// Copyright 2026 olga-safonova. Licensed under Apache-2.0. See LICENSE.
//
// Hand-authored — extracted from helpers.go during the cohesion-split
// refactor. Do not re-add the "Generated by CLI Printing Press" marker;
// the regenmerge pass uses that marker to decide what to clobber.
//
// Responsibility: render JSON arrays/objects to a terminal as either a
// tab-aligned table or a per-item card layout, including the field
// prioritization that decides column order.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"sort"
	"strings"
	"text/tabwriter"
	"unicode"
)

func newTabWriter(w io.Writer) *tabwriter.Writer {
	return tabwriter.NewWriter(w, 2, 4, 2, ' ', 0)
}

// wantsHumanTable returns true when output should be a human-friendly table.
// Smart default: terminal=table, pipe=JSON.
//   - Human in terminal: isTerminal()=true → table
//   - Claude Code/Codex bash tool: stdout piped → JSON
//   - --json/--csv/--compact/--agent: machine format → JSON
func wantsHumanTable(w io.Writer, flags *rootFlags) bool {
	if flags.asJSON || flags.csv || flags.compact || flags.quiet || flags.plain {
		return false
	}
	if flags.selectFields != "" {
		return false
	}
	return isTerminal(w)
}

func printAutoTable(w io.Writer, items []map[string]any) error {
	if len(items) == 0 {
		return nil
	}

	// Count scalar vs complex fields to decide format
	scalarCount := 0
	for _, v := range items[0] {
		switch v.(type) {
		case string, float64, bool, nil:
			scalarCount++
		}
	}

	// Use sectional/card layout for complex items (many fields or nested data)
	if len(items[0]) > 8 || scalarCount < len(items[0])-2 {
		return printAutoCards(w, items)
	}

	headers := prioritizeHeaders(items[0])

	// Limit to 6 columns max for readability
	if len(headers) > 6 {
		headers = headers[:6]
	}

	// Build rows
	rows := make([][]string, 0, len(items))
	for _, item := range items {
		row := make([]string, len(headers))
		for i, h := range headers {
			row[i] = formatCellValue(item[h])
		}
		rows = append(rows, row)
	}

	// Print with tab alignment using tabwriter
	tw := newTabWriter(w)
	upperHeaders := make([]string, len(headers))
	for i, h := range headers {
		upperHeaders[i] = bold(strings.ToUpper(h))
	}

	fmt.Fprintln(tw, strings.Join(upperHeaders, "\t"))
	for _, row := range rows {
		fmt.Fprintln(tw, strings.Join(row, "\t"))
	}
	return tw.Flush()
}

// prioritizeHeaders orders scalar fields by importance for table display.
func prioritizeHeaders(item map[string]any) []string {
	return prioritizeFields(item, false)
}

// prioritizeAllHeaders orders all fields (including arrays) by importance for card display.
func prioritizeAllHeaders(item map[string]any) []string {
	return prioritizeFields(item, true)
}

// prioritizeFields orders fields by importance: identity → temporal → status → other.
// When includeComplex is true, arrays and objects are included (for card layout).
//
// Uses exact-or-suffix matching to avoid false positives: "name" matches "Name" and
// "UserName" but not "BuildingName" (because "Building" is not a known prefix that
// indicates identity). The field is split on camelCase/snake_case boundaries and the
// LAST segment is matched against patterns.
func prioritizeFields(item map[string]any, includeComplex bool) []string {
	exactMatches := map[string]int{
		"id": 0, "name": 0, "title": 0, "slug": 0, "key": 0,
		"date": 1, "created": 1, "updated": 1, "createdat": 1, "updatedat": 1,
		"status": 2, "state": 2, "statuscode": 2,
		"summary": 3, "description": 3, "price": 3, "amount": 3, "total": 3,
		"cost": 3, "points": 3, "score": 3,
		"type": 4, "kind": 4, "category": 4, "email": 4, "phone": 4, "url": 4,
	}
	suffixMatches := map[string]int{
		"id": 0, "name": 0, "title": 0,
		"date": 1, "time": 1,
		"status": 2, "state": 2, "code": 2,
		"price": 3, "amount": 3, "total": 3, "cost": 3,
		"summary": 3, "description": 3, "points": 3, "score": 3,
		"type": 4, "kind": 4, "category": 4, "method": 4,
	}

	numTiers := 5

	type scored struct {
		name  string
		tier  int
		index int
	}

	var all []scored
	idx := 0
	for k, v := range item {
		if !includeComplex {
			switch v.(type) {
			case []any, map[string]any:
				continue
			}
		}
		if includeComplex && formatCellValue(v) == "" {
			continue
		}

		tier := tierForFieldName(k, exactMatches, suffixMatches, numTiers)

		// Demote booleans to last
		if _, ok := v.(bool); ok && tier >= numTiers {
			tier = numTiers + 1
		}
		all = append(all, scored{name: k, tier: tier, index: idx})
		idx++
	}

	sort.Slice(all, func(i, j int) bool {
		if all[i].tier != all[j].tier {
			return all[i].tier < all[j].tier
		}
		return all[i].index < all[j].index
	})

	headers := make([]string, len(all))
	for i, s := range all {
		headers[i] = s.name
	}
	return headers
}

// tierForFieldName classifies a field name into a priority tier. Extracted from
// prioritizeFields' inner block to flatten the nested decision tree (the
// CodeScene "Bumpy Road" + "Deep Nesting" smells in the original).
func tierForFieldName(field string, exactMatches, suffixMatches map[string]int, numTiers int) int {
	lower := strings.ToLower(field)
	if t, ok := exactMatches[lower]; ok {
		return t
	}
	segments := splitCamelCase(lower)
	if len(segments) == 0 {
		return numTiers
	}
	lastSeg := segments[len(segments)-1]
	t, ok := suffixMatches[lastSeg]
	if !ok {
		return numTiers
	}
	// Compound names with identity suffixes (BuildingName, TipTime) get
	// demoted one tier because the prefix dilutes the signal.
	if len(segments) > 1 {
		return t + 1
	}
	return t
}

// splitCamelCase splits "OrderDate" → ["order", "date"], "statusCode" → ["status", "code"],
// "page_size" → ["page", "size"].
func splitCamelCase(s string) []string {
	var segments []string
	var current strings.Builder
	runes := []rune(s)
	for i, r := range runes {
		if r == '_' || r == '-' {
			if current.Len() > 0 {
				segments = append(segments, current.String())
				current.Reset()
			}
			continue
		}
		if i > 0 && unicode.IsUpper(r) && unicode.IsLower(runes[i-1]) {
			if current.Len() > 0 {
				segments = append(segments, current.String())
				current.Reset()
			}
		}
		current.WriteRune(unicode.ToLower(r))
	}
	if current.Len() > 0 {
		segments = append(segments, current.String())
	}
	return segments
}

// printAutoCards renders items as labeled cards — one block per item.
// Used for complex responses with many fields or nested data.
func printAutoCards(w io.Writer, items []map[string]any) error {
	headers := prioritizeAllHeaders(items[0])

	// Find the longest header for alignment
	maxLen := 0
	for _, h := range headers {
		if len(h) > maxLen {
			maxLen = len(h)
		}
	}

	for i, item := range items {
		if i > 0 {
			fmt.Fprintln(w)
		}
		printCardHeader(w, item, headers)
		for _, h := range headers[2:] {
			printCardField(w, h, item[h], maxLen)
		}
	}
	return nil
}

// printCardHeader renders the title line of a single card.
func printCardHeader(w io.Writer, item map[string]any, headers []string) {
	titleVal := formatCellValue(item[headers[0]])
	upper := bold(strings.ToUpper(headers[0]))
	if len(headers) > 1 {
		secondVal := formatCellValue(item[headers[1]])
		if secondVal != "" {
			fmt.Fprintf(w, "%s %s — %s\n", upper, titleVal, secondVal)
			return
		}
	}
	fmt.Fprintf(w, "%s %s\n", upper, titleVal)
}

// printCardField renders one indented field within a card, skipping empty/zero values.
func printCardField(w io.Writer, label string, raw any, maxLen int) {
	v := formatCellValue(raw)
	if isEmptyCardValue(v) {
		return
	}
	// Multi-line values (nested arrays) start with \n
	if strings.HasPrefix(v, "\n") {
		fmt.Fprintf(w, "  %s:%s\n", label, v)
		return
	}
	fmt.Fprintf(w, "  %-*s  %s\n", maxLen, label+":", v)
}

func isEmptyCardValue(v string) bool {
	switch v {
	case "", "false", "0", "[]", "null":
		return true
	}
	return false
}

// formatCellValue renders any JSON-decoded value as a single-cell string.
func formatCellValue(v any) string {
	switch val := v.(type) {
	case string:
		return formatCellString(val)
	case float64:
		return formatCellFloat(val)
	case bool:
		return fmt.Sprintf("%t", val)
	case nil:
		return ""
	case []any:
		return formatCellArray(val)
	case map[string]any:
		return formatSingleObject(val)
	default:
		b, _ := json.Marshal(val)
		return truncate(string(b), 60)
	}
}

func formatCellString(s string) string {
	// Format ISO dates as just the date portion.
	if len(s) >= 19 && s[4] == '-' && s[7] == '-' && s[10] == 'T' {
		return s[:10]
	}
	return truncate(s, 60)
}

func formatCellFloat(f float64) string {
	if f == float64(int64(f)) {
		return fmt.Sprintf("%d", int64(f))
	}
	return fmt.Sprintf("%.2f", f)
}

func formatCellArray(items []any) string {
	if len(items) == 0 {
		return ""
	}
	// If array contains objects, format each as a summary line.
	if _, isObj := items[0].(map[string]any); isObj {
		return formatObjectArray(items)
	}
	// Flatten simple arrays into comma-separated string.
	parts := make([]string, 0, len(items))
	for _, item := range items {
		if s, ok := item.(string); ok {
			parts = append(parts, s)
			continue
		}
		b, _ := json.Marshal(item)
		parts = append(parts, string(b))
	}
	return truncate(strings.Join(parts, ", "), 60)
}

// formatObjectArray renders an array of objects as a multi-line summary.
func formatObjectArray(items []any) string {
	var lines []string
	for _, raw := range items {
		obj, ok := raw.(map[string]any)
		if !ok {
			continue
		}
		lines = append(lines, formatObjectSummary(obj))
	}
	if len(lines) == 0 {
		return ""
	}
	// Multi-line: newline-prefixed so the card renderer can indent.
	return "\n" + strings.Join(lines, "\n")
}

// formatObjectSummary extracts the most useful fields from an object into a one-line summary.
// Looks for: qty/count → name/title → size → price, in that order.
func formatObjectSummary(obj map[string]any) string {
	var parts []string

	if qty := summaryQty(obj); qty != "" {
		parts = append(parts, qty)
	}
	if name := summaryName(obj); name != "" {
		parts = append(parts, name)
	}
	if size := summarySize(obj); size != "" {
		parts = append(parts, "—", size)
	}
	if price := summaryPrice(obj); price != "" {
		parts = append(parts, price)
	}

	if len(parts) == 0 {
		// Fallback: JSON summary
		b, _ := json.Marshal(obj)
		return truncate(string(b), 80)
	}
	return "    " + strings.Join(parts, " ")
}

func summaryQty(obj map[string]any) string {
	qty := findField(obj, "qty", "count", "quantity")
	if qty == "" || qty == "0" {
		return ""
	}
	return qty + "x"
}

func summaryName(obj map[string]any) string {
	if name := findField(obj, "name", "title", "label", "description"); name != "" {
		return name
	}
	// Check nested objects for name.
	for _, key := range []string{"Side1", "side1", "Item", "item", "Product", "product"} {
		nested, ok := obj[key].(map[string]any)
		if !ok {
			continue
		}
		if name := findField(nested, "name", "title", "label"); name != "" {
			return name
		}
	}
	return ""
}

func summarySize(obj map[string]any) string {
	if size := findField(obj, "sizename", "size_name"); size != "" {
		return size
	}
	return findField(obj, "catname", "cat_name", "category")
}

func summaryPrice(obj map[string]any) string {
	price := findField(obj, "extprice", "price", "amount", "total")
	if price == "" || price == "0" {
		return ""
	}
	return fmt.Sprintf("($%s)", price)
}

// formatSingleObject renders a single object by its most descriptive fields.
func formatSingleObject(obj map[string]any) string {
	if name := findField(obj, "name", "title", "label", "description"); name != "" {
		return name
	}
	if id := findField(obj, "id", "key", "code"); id != "" {
		return id
	}
	return ""
}

// findField searches an object for a field name (case-insensitive) and returns its formatted value.
func findField(obj map[string]any, names ...string) string {
	for _, name := range names {
		for k, v := range obj {
			if strings.EqualFold(k, name) {
				return formatCellValue(v)
			}
		}
	}
	return ""
}
