// Copyright 2026 olga-safonova. Licensed under Apache-2.0. See LICENSE.
//
// Hand-authored — extracted from helpers.go during the cohesion-split
// refactor. Do not re-add the "Generated by CLI Printing Press" marker;
// the regenmerge pass uses that marker to decide what to clobber.
//
// Responsibility: render JSON arrays as CSV with a header row.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"sort"
	"strings"
)

// printCSV renders JSON arrays as CSV with header row.
func printCSV(w io.Writer, data json.RawMessage) error {
	var items []map[string]any
	if err := json.Unmarshal(data, &items); err != nil || len(items) == 0 {
		// Single object or empty - just print as JSON
		fmt.Fprintln(w, string(data))
		return nil
	}
	keys := collectCSVKeys(items)
	fmt.Fprintln(w, strings.Join(keys, ","))
	for _, item := range items {
		fmt.Fprintln(w, strings.Join(rowForItem(item, keys), ","))
	}
	return nil
}

func collectCSVKeys(items []map[string]any) []string {
	keySet := map[string]bool{}
	for _, item := range items {
		for k := range item {
			keySet[k] = true
		}
	}
	keys := make([]string, 0, len(keySet))
	for k := range keySet {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func rowForItem(item map[string]any, keys []string) []string {
	vals := make([]string, len(keys))
	for i, k := range keys {
		vals[i] = csvCell(item[k])
	}
	return vals
}

func csvCell(v any) string {
	if v == nil {
		return ""
	}
	s := fmt.Sprintf("%v", v)
	if strings.ContainsAny(s, ",\"\n") {
		return `"` + strings.ReplaceAll(s, `"`, `""`) + `"`
	}
	return s
}
