// Copyright 2026 olga-safonova. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newResourceTypesGetCmd(flags *rootFlags) *cobra.Command {
	var flagResource string

	cmd := &cobra.Command{
		Use:         "get",
		Short:       "Retrieve metadata for the available resource types (User and Group) that are supported.",
		Example:     "  miro-developer-platform-pp-cli resource-types get",
		Annotations: map[string]string{"pp:endpoint": "resource-types.get", "pp:method": "GET", "pp:path": "/ResourceTypes/{resource}", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if cmd.Flags().Changed("resource") {
				allowedResource := []string{"User", "Group"}
				validResource := false
				for _, v := range allowedResource {
					if flagResource == v {
						validResource = true
						break
					}
				}
				if !validResource {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "resource", flagResource, allowedResource)
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/ResourceTypes/{resource}"
			path = replacePathParam(path, "resource", fmt.Sprintf("%v", flagResource))
			params := map[string]string{}
			data, prov, err := resolveRead(cmd.Context(), c, flags, "resource-types", false, path, params, nil)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Unwrap single-key array-wrapper responses (e.g. {"tags":[...]},
			// {"items":[...]}) so the count, table, and provenance envelope all
			// see the inner list. Multi-key wrappers (paginated lists with
			// cursor/total fields) pass through unchanged.
			data = unwrapListResponse(data)
			// Print provenance to stderr for human-facing output
			{
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested.
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagResource, "resource", "User", "Resource (one of: User, Group)")

	return cmd
}
