// Copyright 2026 olga-safonova. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newResourceTypesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "resource-types",
		Short: "Manage resource types",
	}

	cmd.AddCommand(newResourceTypesGetCmd(flags))
	cmd.AddCommand(newResourceTypesListCmd(flags))
	return cmd
}
