// Copyright 2026 olga-safonova. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newUsersReplaceCmd(flags *rootFlags) *cobra.Command {
	var bodyActive bool
	var bodyDisplayName string
	var bodyEmails string
	var bodyGroups string
	var bodyMeta string
	var bodyName string
	var bodyPhotos string
	var bodyPreferredLanguage string
	var bodyRoles string
	var bodySchemas string
	var bodyUrnIetfParamsScimSchemasExtensionEnterprise20User string
	var bodyUserName string
	var bodyUserType string
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "replace <id>",
		Short:       "Updates an existing user resource. This is the easiest way to replace user information. <br><br> If the user is...",
		Example:     "  miro-developer-platform-pp-cli users replace 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "users.replace", "pp:method": "PUT", "pp:path": "/Users/{id}"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			if !stdinBody {
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/Users/{id}"
			path = replacePathParam(path, "id", args[0])
			var body any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				if err := json.Unmarshal(stdinData, &body); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
			} else {
				bodyFields := map[string]any{}
				if bodyActive != false {
					bodyFields["active"] = bodyActive
				}
				if bodyDisplayName != "" {
					bodyFields["displayName"] = bodyDisplayName
				}
				if bodyEmails != "" {
					var parsedEmails any
					if err := json.Unmarshal([]byte(bodyEmails), &parsedEmails); err != nil {
						return fmt.Errorf("parsing --emails JSON: %w", err)
					}
					bodyFields["emails"] = parsedEmails
				}
				if bodyGroups != "" {
					var parsedGroups any
					if err := json.Unmarshal([]byte(bodyGroups), &parsedGroups); err != nil {
						return fmt.Errorf("parsing --groups JSON: %w", err)
					}
					bodyFields["groups"] = parsedGroups
				}
				if bodyMeta != "" {
					var parsedMeta any
					if err := json.Unmarshal([]byte(bodyMeta), &parsedMeta); err != nil {
						return fmt.Errorf("parsing --meta JSON: %w", err)
					}
					bodyFields["meta"] = parsedMeta
				}
				if bodyName != "" {
					var parsedName any
					if err := json.Unmarshal([]byte(bodyName), &parsedName); err != nil {
						return fmt.Errorf("parsing --name JSON: %w", err)
					}
					bodyFields["name"] = parsedName
				}
				if bodyPhotos != "" {
					var parsedPhotos any
					if err := json.Unmarshal([]byte(bodyPhotos), &parsedPhotos); err != nil {
						return fmt.Errorf("parsing --photos JSON: %w", err)
					}
					bodyFields["photos"] = parsedPhotos
				}
				if bodyPreferredLanguage != "" {
					bodyFields["preferredLanguage"] = bodyPreferredLanguage
				}
				if bodyRoles != "" {
					var parsedRoles any
					if err := json.Unmarshal([]byte(bodyRoles), &parsedRoles); err != nil {
						return fmt.Errorf("parsing --roles JSON: %w", err)
					}
					bodyFields["roles"] = parsedRoles
				}
				if bodySchemas != "" {
					var parsedSchemas any
					if err := json.Unmarshal([]byte(bodySchemas), &parsedSchemas); err != nil {
						return fmt.Errorf("parsing --schemas JSON: %w", err)
					}
					bodyFields["schemas"] = parsedSchemas
				}
				if bodyUrnIetfParamsScimSchemasExtensionEnterprise20User != "" {
					var parsedUrnIetfParamsScimSchemasExtensionEnterprise20User any
					if err := json.Unmarshal([]byte(bodyUrnIetfParamsScimSchemasExtensionEnterprise20User), &parsedUrnIetfParamsScimSchemasExtensionEnterprise20User); err != nil {
						return fmt.Errorf("parsing --urn-ietf-params-scim-schemas-extension-enterprise-2-0-user JSON: %w", err)
					}
					bodyFields["urn:ietf:params:scim:schemas:extension:enterprise:2.0:User"] = parsedUrnIetfParamsScimSchemasExtensionEnterprise20User
				}
				if bodyUserName != "" {
					bodyFields["userName"] = bodyUserName
				}
				if bodyUserType != "" {
					bodyFields["userType"] = bodyUserType
				}
				body = bodyFields
			}
			data, statusCode, err := c.Put(path, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							return nil
						}
					}
				}
			}
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				if flags.quiet {
					return nil
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				envelope := map[string]any{
					"action":   "put",
					"resource": "users",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300,
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				return printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true)
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().BoolVar(&bodyActive, "active", false, "Indicates whether the user is active or deactivated in the organization.")
	cmd.Flags().StringVar(&bodyDisplayName, "display-name", "", "A human-readable name for the user, typically the full name.")
	cmd.Flags().StringVar(&bodyEmails, "emails", "", "An array of email addresses, each an object with a value, display and primary flag.")
	cmd.Flags().StringVar(&bodyGroups, "groups", "", "An array of groups (teams) the user belongs to in the organization. Contains id and display name of the team.")
	cmd.Flags().StringVar(&bodyMeta, "meta", "", "Metadata about the resource.")
	cmd.Flags().StringVar(&bodyName, "name", "", "Structured object for the person’s name. This includes the family name (last name), and given name (first name).")
	cmd.Flags().StringVar(&bodyPhotos, "photos", "", "An array for profile pictures, contains type.")
	cmd.Flags().StringVar(&bodyPreferredLanguage, "preferred-language", "", "Specifies the users preferred language. <br><br> Example: en_US for English.")
	cmd.Flags().StringVar(&bodyRoles, "roles", "", "An array of roles assigned to the user in the organization. Contains role type, value, display and primary flag.")
	cmd.Flags().StringVar(&bodySchemas, "schemas", "", "Identifies which schema(s) this resource uses. In this case it is the SCIM core User schema.")
	cmd.Flags().StringVar(&bodyUrnIetfParamsScimSchemasExtensionEnterprise20User, "urn-ietf-params-scim-schemas-extension-enterprise-2-0-user", "", "Enterprise User extension schema.")
	cmd.Flags().StringVar(&bodyUserName, "user-name", "", "The unique username/login identifier. An email address in this case.")
	cmd.Flags().StringVar(&bodyUserType, "user-type", "", "Free-form string to indicate the user license type in the organization.")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
