// Copyright 2026 olga-safonova. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newUsersCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "users",
		Short: "Manage users",
	}

	cmd.AddCommand(newUsersCreateCmd(flags))
	cmd.AddCommand(newUsersDeleteCmd(flags))
	cmd.AddCommand(newUsersGetCmd(flags))
	cmd.AddCommand(newUsersListCmd(flags))
	cmd.AddCommand(newUsersPatchCmd(flags))
	cmd.AddCommand(newUsersReplaceCmd(flags))
	return cmd
}
