// Copyright 2026 olga-safonova. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newV2ExperimentalGetMetricsCmd(flags *rootFlags) *cobra.Command {
	var flagStartDate string
	var flagEndDate string
	var flagPeriod string

	cmd := &cobra.Command{
		Use:         "get-metrics <app_id>",
		Short:       "Returns a list of usage metrics for a specific app for a given time range, grouped by requested time period. This...",
		Example:     "  miro-cli v2-experimental get-metrics 550e8400-e29b-41d4-a716-446655440000 --start-date 2026-01-15 --end-date 2026-01-15",
		Annotations: map[string]string{"pp:endpoint": "v2-experimental.get-metrics", "pp:method": "GET", "pp:path": "/v2-experimental/apps/{app_id}/metrics", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			if !cmd.Flags().Changed("start-date") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "start-date")
			}
			if !cmd.Flags().Changed("end-date") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "end-date")
			}
			if cmd.Flags().Changed("period") {
				allowedPeriod := []string{"DAY", "WEEK", "MONTH"}
				validPeriod := false
				for _, v := range allowedPeriod {
					if flagPeriod == v {
						validPeriod = true
						break
					}
				}
				if !validPeriod {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "period", flagPeriod, allowedPeriod)
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/v2-experimental/apps/{app_id}/metrics"
			path = replacePathParam(path, "app_id", args[0])
			params := map[string]string{}
			if flagStartDate != "" {
				params["startDate"] = fmt.Sprintf("%v", flagStartDate)
			}
			if flagEndDate != "" {
				params["endDate"] = fmt.Sprintf("%v", flagEndDate)
			}
			if flagPeriod != "" {
				params["period"] = fmt.Sprintf("%v", flagPeriod)
			}
			data, prov, err := resolveRead(cmd.Context(), c, flags, "v2-experimental", false, path, params, nil)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Unwrap single-key array-wrapper responses (e.g. {"tags":[...]},
			// {"items":[...]}) so the count, table, and provenance envelope all
			// see the inner list. Multi-key wrappers (paginated lists with
			// cursor/total fields) pass through unchanged.
			data = unwrapListResponse(data)
			// Print provenance to stderr for human-facing output
			{
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested.
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagStartDate, "start-date", "", "Start date of the period in UTC format. For example, 2024-12-31.")
	cmd.Flags().StringVar(&flagEndDate, "end-date", "", "End date of the period in UTC format. For example, 2024-12-31.")
	cmd.Flags().StringVar(&flagPeriod, "period", "WEEK", "Group data by this time period. (one of: DAY, WEEK, MONTH)")

	return cmd
}
