// Copyright 2026 olga-safonova. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newV2ExperimentalCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "v2-experimental",
		Short: "Manage v2 experimental",
	}

	cmd.AddCommand(newV2ExperimentalCreateCodeWidgetItemCmd(flags))
	cmd.AddCommand(newV2ExperimentalCreateMindmapNodesExperimentalCmd(flags))
	cmd.AddCommand(newV2ExperimentalCreateShapeItemFlowchartCmd(flags))
	cmd.AddCommand(newV2ExperimentalDeleteCodeWidgetItemCmd(flags))
	cmd.AddCommand(newV2ExperimentalDeleteItemExperimentalCmd(flags))
	cmd.AddCommand(newV2ExperimentalDeleteMindmapNodeExperimentalCmd(flags))
	cmd.AddCommand(newV2ExperimentalDeleteShapeItemFlowchartCmd(flags))
	cmd.AddCommand(newV2ExperimentalGetCodeWidgetItemCmd(flags))
	cmd.AddCommand(newV2ExperimentalGetCodeWidgetItemsCmd(flags))
	cmd.AddCommand(newV2ExperimentalGetItemsExperimentalCmd(flags))
	cmd.AddCommand(newV2ExperimentalGetMetricsCmd(flags))
	cmd.AddCommand(newV2ExperimentalGetMetricsTotalCmd(flags))
	cmd.AddCommand(newV2ExperimentalGetMindmapNodeExperimentalCmd(flags))
	cmd.AddCommand(newV2ExperimentalGetMindmapNodesExperimentalCmd(flags))
	cmd.AddCommand(newV2ExperimentalGetShapeItemFlowchartCmd(flags))
	cmd.AddCommand(newV2ExperimentalGetSpecificItemExperimentalCmd(flags))
	cmd.AddCommand(newV2ExperimentalMoveCodeWidgetItemCmd(flags))
	cmd.AddCommand(newV2ExperimentalUpdateCodeWidgetItemCmd(flags))
	cmd.AddCommand(newV2ExperimentalUpdateShapeItemFlowchartCmd(flags))
	return cmd
}
