// Copyright 2026 olga-safonova. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newV2ExperimentalMoveCodeWidgetItemCmd(flags *rootFlags) *cobra.Command {
	var bodyX float64
	var bodyY float64
	var stdinBody bool

	cmd := &cobra.Command{
		Use:   "move-code-widget-item <board_id> <item_id>",
		Aliases: []string{"update"},
		Short: "Updates the position of a code widget item on a board.<br/><h3>Required scope</h3> <a target=_blank...",
		Example: "  miro-developer-platform-pp-cli v2-experimental move-code-widget-item 550e8400-e29b-41d4-a716-446655440000 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "v2-experimental.move-code-widget-item", "pp:method": "PATCH", "pp:path": "/v2-experimental/boards/{board_id}/code_widgets/{item_id}/position"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			if !stdinBody {
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/v2-experimental/boards/{board_id}/code_widgets/{item_id}/position"
			path = replacePathParam(path, "board_id", args[0])
			if len(args) < 2 {
				return usageErr(fmt.Errorf("item_id is required\nUsage: %s <%s>", cmd.CommandPath(), "item_id"))
			}
			path = replacePathParam(path, "item_id", args[1])
			var body any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				if err := json.Unmarshal(stdinData, &body); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
			} else {
				bodyFields := map[string]any{}
				if bodyX != 0.0 {
					bodyFields["x"] = bodyX
				}
				if bodyY != 0.0 {
					bodyFields["y"] = bodyY
				}
				body = bodyFields
			}
			data, statusCode, err := c.Patch(path, body)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						return nil
					}
				} else {
					var wrapped struct{ Data []map[string]any `json:"data"` }
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							return nil
						}
					}
				}
			}
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				if flags.quiet {
					return nil
				}
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				envelope := map[string]any{
					"action":   "patch",
					"resource": "v2-experimental",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300,
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						envelope["data"] = parsed
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				return printOutput(cmd.OutOrStdout(), json.RawMessage(envelopeJSON), true)
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().Float64Var(&bodyX, "x", 0.000000, "X-axis coordinate of the location of the item on the board. By default, all items have absolute positioning to the...")
	cmd.Flags().Float64Var(&bodyY, "y", 0.000000, "Y-axis coordinate of the location of the item on the board. By default, all items have absolute positioning to the...")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
